--
-- PostgreSQL database dump
--

\restrict KtgNhHej0QunVRxf5r3JuD4HYlXKjQ6td0dXZISBZKfXPh25Efp4EfmZckbeONK

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assessments_answerchoice; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.assessments_answerchoice (
    id bigint NOT NULL,
    text character varying(200) NOT NULL,
    value integer NOT NULL
);


ALTER TABLE public.assessments_answerchoice OWNER TO careeratlas_user;

--
-- Name: assessments_answerchoice_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.assessments_answerchoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_answerchoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments_assessmentresult; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.assessments_assessmentresult (
    id bigint NOT NULL,
    ei_score numeric(5,3) NOT NULL,
    sn_score numeric(5,3) NOT NULL,
    tf_score numeric(5,3) NOT NULL,
    jp_score numeric(5,3) NOT NULL,
    confidence numeric(3,2) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.assessments_assessmentresult OWNER TO careeratlas_user;

--
-- Name: assessments_assessmentresult_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.assessments_assessmentresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_assessmentresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments_assessmentsession; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.assessments_assessmentsession (
    id bigint NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    is_completed boolean NOT NULL
);


ALTER TABLE public.assessments_assessmentsession OWNER TO careeratlas_user;

--
-- Name: assessments_assessmentsession_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.assessments_assessmentsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_assessmentsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments_mbtidimension; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.assessments_mbtidimension (
    id bigint NOT NULL,
    code character varying(2) NOT NULL,
    dimension_a character varying(50) NOT NULL,
    dimension_b character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.assessments_mbtidimension OWNER TO careeratlas_user;

--
-- Name: assessments_mbtidimension_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.assessments_mbtidimension ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_mbtidimension_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments_personalitytype; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.assessments_personalitytype (
    id bigint NOT NULL,
    mbti_type character varying(4) NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    strengths text NOT NULL,
    weaknesses text NOT NULL,
    career_recommendations text NOT NULL
);


ALTER TABLE public.assessments_personalitytype OWNER TO careeratlas_user;

--
-- Name: assessments_personalitytype_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.assessments_personalitytype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_personalitytype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments_question; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.assessments_question (
    id bigint NOT NULL,
    text text NOT NULL,
    category character varying(2) NOT NULL,
    dimension_a_weight integer NOT NULL,
    dimension_b_weight integer NOT NULL
);


ALTER TABLE public.assessments_question OWNER TO careeratlas_user;

--
-- Name: assessments_question_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.assessments_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments_questionresponse; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.assessments_questionresponse (
    id bigint NOT NULL,
    response_time integer NOT NULL
);


ALTER TABLE public.assessments_questionresponse OWNER TO careeratlas_user;

--
-- Name: assessments_questionresponse_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.assessments_questionresponse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_questionresponse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO careeratlas_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO careeratlas_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO careeratlas_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO careeratlas_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO careeratlas_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO careeratlas_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO careeratlas_user;

--
-- Name: recommendations_career; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_career (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    description text NOT NULL,
    category character varying(100) NOT NULL,
    average_salary numeric(10,2),
    job_outlook character varying(50) NOT NULL,
    kenyan_market_demand character varying(50) NOT NULL
);


ALTER TABLE public.recommendations_career OWNER TO careeratlas_user;

--
-- Name: recommendations_career_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_career ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_career_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_career_recommended_subjects; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_career_recommended_subjects (
    id bigint NOT NULL,
    career_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


ALTER TABLE public.recommendations_career_recommended_subjects OWNER TO careeratlas_user;

--
-- Name: recommendations_career_recommended_subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_career_recommended_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_career_recommended_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_career_required_subjects; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_career_required_subjects (
    id bigint NOT NULL,
    career_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


ALTER TABLE public.recommendations_career_required_subjects OWNER TO careeratlas_user;

--
-- Name: recommendations_career_required_subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_career_required_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_career_required_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_careerpersonalitymatch; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_careerpersonalitymatch (
    id bigint NOT NULL,
    compatibility_score numeric(3,2) CONSTRAINT recommendations_careerpersonalitym_compatibility_score_not_null NOT NULL,
    reasoning text NOT NULL,
    career_id bigint NOT NULL,
    personality_type_id bigint CONSTRAINT recommendations_careerpersonalitym_personality_type_id_not_null NOT NULL
);


ALTER TABLE public.recommendations_careerpersonalitymatch OWNER TO careeratlas_user;

--
-- Name: recommendations_careerpersonalitymatch_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_careerpersonalitymatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_careerpersonalitymatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_learningstyle; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_learningstyle (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    study_recommendations text NOT NULL
);


ALTER TABLE public.recommendations_learningstyle OWNER TO careeratlas_user;

--
-- Name: recommendations_learningstyle_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_learningstyle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_learningstyle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_learningstyle_personality_types; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_learningstyle_personality_types (
    id bigint NOT NULL,
    learningstyle_id bigint CONSTRAINT recommendations_learningstyle_persona_learningstyle_id_not_null NOT NULL,
    personalitytype_id bigint CONSTRAINT recommendations_learningstyle_perso_personalitytype_id_not_null NOT NULL
);


ALTER TABLE public.recommendations_learningstyle_personality_types OWNER TO careeratlas_user;

--
-- Name: recommendations_learningstyle_personality_types_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_learningstyle_personality_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_learningstyle_personality_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_studentrecommendation; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_studentrecommendation (
    id bigint NOT NULL,
    personality_match_score numeric(3,2) CONSTRAINT recommendations_studentrecomme_personality_match_score_not_null NOT NULL,
    academic_match_score numeric(3,2),
    overall_score numeric(3,2) NOT NULL,
    reasoning text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    career_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.recommendations_studentrecommendation OWNER TO careeratlas_user;

--
-- Name: recommendations_studentrecommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_studentrecommendation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_studentrecommendation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_studentrecommendation_recommended_subjects; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_studentrecommendation_recommended_subjects (
    id bigint CONSTRAINT recommendations_studentrecommendation_recommended_s_id_not_null NOT NULL,
    studentrecommendation_id bigint CONSTRAINT recommendations_studentrecomm_studentrecommendation_id_not_null NOT NULL,
    subject_id bigint CONSTRAINT recommendations_studentrecommendation_recom_subject_id_not_null NOT NULL
);


ALTER TABLE public.recommendations_studentrecommendation_recommended_subjects OWNER TO careeratlas_user;

--
-- Name: recommendations_studentrecommendation_recommended_subjec_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_studentrecommendation_recommended_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_studentrecommendation_recommended_subjec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendations_subject; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.recommendations_subject (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(20) NOT NULL,
    category character varying(50) NOT NULL,
    difficulty_level character varying(20) NOT NULL
);


ALTER TABLE public.recommendations_subject OWNER TO careeratlas_user;

--
-- Name: recommendations_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.recommendations_subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendations_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    user_type character varying(20) NOT NULL,
    phone_number character varying(15) NOT NULL,
    date_of_birth date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_customuser OWNER TO careeratlas_user;

--
-- Name: users_customuser_groups; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.users_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_customuser_groups OWNER TO careeratlas_user;

--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.users_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_user_permissions; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.users_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_customuser_user_permissions OWNER TO careeratlas_user;

--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.users_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_school; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.users_school (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    code character varying(20) NOT NULL,
    county character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_school OWNER TO careeratlas_user;

--
-- Name: users_school_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.users_school ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_studentprofile; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.users_studentprofile (
    id bigint NOT NULL,
    grade_level character varying(50) NOT NULL,
    career_aspirations text NOT NULL,
    kcpe_score numeric(5,2),
    kcse_score character varying(10) NOT NULL,
    school_id bigint,
    user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users_studentprofile OWNER TO careeratlas_user;

--
-- Name: users_studentprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.users_studentprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_studentprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_studentprofile_subjects; Type: TABLE; Schema: public; Owner: careeratlas_user
--

CREATE TABLE public.users_studentprofile_subjects (
    id bigint NOT NULL,
    studentprofile_id bigint NOT NULL,
    subject_id bigint NOT NULL
);


ALTER TABLE public.users_studentprofile_subjects OWNER TO careeratlas_user;

--
-- Name: users_studentprofile_subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: careeratlas_user
--

ALTER TABLE public.users_studentprofile_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_studentprofile_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: assessments_answerchoice; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.assessments_answerchoice (id, text, value) FROM stdin;
\.


--
-- Data for Name: assessments_assessmentresult; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.assessments_assessmentresult (id, ei_score, sn_score, tf_score, jp_score, confidence, created_at) FROM stdin;
1	-3.000	1.000	3.000	-3.000	0.17	2025-11-22 13:49:29.899881+03
2	-2.000	3.000	-3.000	1.000	0.15	2025-11-22 16:28:58.592969+03
3	2.000	1.000	-3.000	-4.000	0.17	2025-11-22 16:39:09.777582+03
4	3.000	3.000	0.000	3.000	0.15	2025-11-22 17:39:57.312799+03
5	3.000	1.000	0.000	6.000	0.17	2025-11-22 18:05:50.726576+03
6	-3.000	3.000	-1.000	6.000	0.22	2025-11-22 18:20:52.138279+03
7	-2.000	-2.000	3.000	-2.000	0.15	2025-11-23 19:23:05.578719+03
8	-3.000	1.000	3.000	1.000	0.13	2025-12-24 14:52:27.152185+03
9	2.000	1.000	0.000	-5.000	0.13	2025-12-25 11:08:52.580988+03
10	3.000	3.000	0.000	1.000	0.12	2025-12-25 13:12:34.551257+03
11	-28.000	-5.000	20.000	8.000	1.00	2025-12-26 18:20:22.750573+03
13	-1.000	2.000	-12.000	3.000	0.30	2025-12-26 21:09:14.367038+03
12	5.000	5.000	-9.000	-31.000	0.83	2025-12-26 18:32:30.619089+03
14	17.000	17.000	-8.000	-21.000	1.00	2025-12-27 15:53:02.955965+03
15	0.000	5.000	26.000	-16.000	0.78	2025-12-27 16:17:23.972405+03
\.


--
-- Data for Name: assessments_assessmentsession; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.assessments_assessmentsession (id, started_at, completed_at, is_completed) FROM stdin;
2	2025-11-22 12:58:55.558109+03	\N	t
3	2025-11-22 13:57:42.833161+03	\N	t
4	2025-11-22 14:00:42.36952+03	\N	t
5	2025-11-22 14:01:15.091658+03	\N	t
6	2025-11-22 16:26:32.035896+03	\N	t
7	2025-11-22 16:37:10.40855+03	\N	t
9	2025-11-22 17:36:42.05745+03	\N	t
10	2025-11-22 18:04:28.718032+03	\N	t
11	2025-11-22 18:09:59.2528+03	\N	f
12	2025-11-22 18:18:04.712441+03	\N	t
13	2025-11-23 19:13:38.45463+03	\N	t
14	2025-12-05 11:37:44.139097+03	\N	f
1	2025-11-22 11:04:58.556278+03	\N	t
15	2025-12-24 16:05:32.560123+03	\N	t
16	2025-12-25 11:07:29.088624+03	\N	t
17	2025-12-25 13:10:30.695688+03	\N	t
18	2025-12-25 13:15:31.500248+03	\N	t
19	2025-12-25 13:22:02.522876+03	\N	f
20	2025-12-26 14:48:50.106841+03	\N	f
21	2025-12-26 16:43:04.622808+03	\N	t
22	2025-12-26 18:31:27.288129+03	\N	t
23	2025-12-26 20:46:29.45178+03	\N	t
24	2025-12-27 10:38:07.778035+03	\N	t
25	2025-12-27 15:29:10.781306+03	\N	t
8	2025-11-22 17:29:00.5254+03	\N	t
\.


--
-- Data for Name: assessments_mbtidimension; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.assessments_mbtidimension (id, code, dimension_a, dimension_b, description) FROM stdin;
1	EI	Extraversion	Introversion	How you interact with others and where you get energy
2	SN	Sensing	Intuition	How you process information and perceive the world
3	TF	Thinking	Feeling	How you make decisions and evaluate information
4	JP	Judging	Perceiving	How you approach life and structure your world
\.


--
-- Data for Name: assessments_personalitytype; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.assessments_personalitytype (id, mbti_type, name, description, strengths, weaknesses, career_recommendations) FROM stdin;
1	INTJ	The Architect	Innovative, strategic thinkers with a plan for everything.	Strategic, knowledgeable, determined, independent	Arrogant, dismissive of emotions, overly critical	Scientists, engineers, professors, judges
2	INTP	The Logician	Innovative inventors with an unquenchable thirst for knowledge.	Analytical, original, open-minded, curious, objective	Insensitive, absent-minded, condescending, impatient	Physicists, programmers, mathematicians, philosophers
3	ENTJ	The Commander	Bold, imaginative and strong-willed leaders, always finding a way.	Efficient, energetic, self-confident, strong-willed, strategic	Impatient, stubborn, dominant, intolerant	CEOs, entrepreneurs, lawyers, consultants
4	ENTP	The Debater	Smart and curious thinkers who cannot resist an intellectual challenge.	Knowledgeable, quick-thinking, original, excellent brainstormers	Argumentative, insensitive, intolerant	Entrepreneurs, lawyers, psychologists, engineers
5	INFJ	The Advocate	Quiet and mystical, yet very inspiring and tireless idealists.	Creative, insightful, principled, passionate, altruistic	Sensitive, extremely private, perfectionistic	Counselors, psychologists, writers, human resources
6	INFP	The Mediator	Poetic, kind and altruistic people, always eager to help a good cause.	Empathetic, creative, idealistic, passionate, open-minded	Unrealistic, self-isolating, unfocused	Writers, artists, psychologists, social workers
7	ENFJ	The Protagonist	Charismatic and inspiring leaders, able to mesmerize their listeners.	Natural leaders, passionate, reliable, charismatic	Overly idealistic, too selfless, fluctuating self-esteem	Teachers, consultants, psychologists, sales
8	ENFP	The Campaigner	Enthusiastic, creative and sociable free spirits, who can always find a reason to smile.	Curious, perceptive, enthusiastic, excellent communicators	Poor practical skills, unfocused, easily stressed	Actors, journalists, consultants, entrepreneurs
\.


--
-- Data for Name: assessments_question; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.assessments_question (id, text, category, dimension_a_weight, dimension_b_weight) FROM stdin;
\.


--
-- Data for Name: assessments_questionresponse; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.assessments_questionresponse (id, response_time) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add school	6	add_school
22	Can change school	6	change_school
23	Can delete school	6	delete_school
24	Can view school	6	view_school
25	Can add user	7	add_customuser
26	Can change user	7	change_customuser
27	Can delete user	7	delete_customuser
28	Can view user	7	view_customuser
29	Can add student profile	8	add_studentprofile
30	Can change student profile	8	change_studentprofile
31	Can delete student profile	8	delete_studentprofile
32	Can view student profile	8	view_studentprofile
33	Can add answer choice	9	add_answerchoice
34	Can change answer choice	9	change_answerchoice
35	Can delete answer choice	9	delete_answerchoice
36	Can view answer choice	9	view_answerchoice
37	Can add assessment result	10	add_assessmentresult
38	Can change assessment result	10	change_assessmentresult
39	Can delete assessment result	10	delete_assessmentresult
40	Can view assessment result	10	view_assessmentresult
41	Can add assessment session	11	add_assessmentsession
42	Can change assessment session	11	change_assessmentsession
43	Can delete assessment session	11	delete_assessmentsession
44	Can view assessment session	11	view_assessmentsession
45	Can add mbti dimension	12	add_mbtidimension
46	Can change mbti dimension	12	change_mbtidimension
47	Can delete mbti dimension	12	delete_mbtidimension
48	Can view mbti dimension	12	view_mbtidimension
49	Can add personality type	13	add_personalitytype
50	Can change personality type	13	change_personalitytype
51	Can delete personality type	13	delete_personalitytype
52	Can view personality type	13	view_personalitytype
53	Can add question	14	add_question
54	Can change question	14	change_question
55	Can delete question	14	delete_question
56	Can view question	14	view_question
57	Can add question response	15	add_questionresponse
58	Can change question response	15	change_questionresponse
59	Can delete question response	15	delete_questionresponse
60	Can view question response	15	view_questionresponse
61	Can add career	16	add_career
62	Can change career	16	change_career
63	Can delete career	16	delete_career
64	Can view career	16	view_career
65	Can add subject	17	add_subject
66	Can change subject	17	change_subject
67	Can delete subject	17	delete_subject
68	Can view subject	17	view_subject
69	Can add career personality match	18	add_careerpersonalitymatch
70	Can change career personality match	18	change_careerpersonalitymatch
71	Can delete career personality match	18	delete_careerpersonalitymatch
72	Can view career personality match	18	view_careerpersonalitymatch
73	Can add learning style	19	add_learningstyle
74	Can change learning style	19	change_learningstyle
75	Can delete learning style	19	delete_learningstyle
76	Can view learning style	19	view_learningstyle
77	Can add student recommendation	20	add_studentrecommendation
78	Can change student recommendation	20	change_studentrecommendation
79	Can delete student recommendation	20	delete_studentrecommendation
80	Can view student recommendation	20	view_studentrecommendation
81	Can add coaching plan	21	add_coachingplan
82	Can change coaching plan	21	change_coachingplan
83	Can delete coaching plan	21	delete_coachingplan
84	Can view coaching plan	21	view_coachingplan
85	Can add conversation	22	add_conversation
86	Can change conversation	22	change_conversation
87	Can delete conversation	22	delete_conversation
88	Can view conversation	22	view_conversation
89	Can add message	23	add_message
90	Can change message	23	change_message
91	Can delete message	23	delete_message
92	Can view message	23	view_message
93	Can add resource recommendation	24	add_resourcerecommendation
94	Can change resource recommendation	24	change_resourcerecommendation
95	Can delete resource recommendation	24	delete_resourcerecommendation
96	Can view resource recommendation	24	view_resourcerecommendation
97	Can add coaching plan	25	add_coachingplan
98	Can change coaching plan	25	change_coachingplan
99	Can delete coaching plan	25	delete_coachingplan
100	Can view coaching plan	25	view_coachingplan
101	Can add coaching session	26	add_coachingsession
102	Can change coaching session	26	change_coachingsession
103	Can delete coaching session	26	delete_coachingsession
104	Can view coaching session	26	view_coachingsession
105	Can add career goal	27	add_careergoal
106	Can change career goal	27	change_careergoal
107	Can delete career goal	27	delete_careergoal
108	Can view career goal	27	view_careergoal
109	Can add action item	28	add_actionitem
110	Can change action item	28	change_actionitem
111	Can delete action item	28	delete_actionitem
112	Can view action item	28	view_actionitem
113	Can add resource recommendation	29	add_resourcerecommendation
114	Can change resource recommendation	29	change_resourcerecommendation
115	Can delete resource recommendation	29	delete_resourcerecommendation
116	Can view resource recommendation	29	view_resourcerecommendation
117	Can add user coaching subscription	30	add_usercoachingsubscription
118	Can change user coaching subscription	30	change_usercoachingsubscription
119	Can delete user coaching subscription	30	delete_usercoachingsubscription
120	Can view user coaching subscription	30	view_usercoachingsubscription
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	school
7	users	customuser
8	users	studentprofile
9	assessments	answerchoice
10	assessments	assessmentresult
11	assessments	assessmentsession
12	assessments	mbtidimension
13	assessments	personalitytype
14	assessments	question
15	assessments	questionresponse
16	recommendations	career
17	recommendations	subject
18	recommendations	careerpersonalitymatch
19	recommendations	learningstyle
20	recommendations	studentrecommendation
21	ai_coach	coachingplan
22	ai_coach	conversation
23	ai_coach	message
24	ai_coach	resourcerecommendation
25	coaching	coachingplan
26	coaching	coachingsession
27	coaching	careergoal
28	coaching	actionitem
29	coaching	resourcerecommendation
30	coaching	usercoachingsubscription
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	assessments	0001_initial	2025-11-20 01:13:02.027489+03
3	contenttypes	0001_initial	2025-11-20 01:13:02.120273+03
4	contenttypes	0002_remove_content_type_name	2025-11-20 01:13:02.139859+03
5	auth	0001_initial	2025-11-20 01:13:02.177322+03
6	auth	0002_alter_permission_name_max_length	2025-11-20 01:13:02.187146+03
7	auth	0003_alter_user_email_max_length	2025-11-20 01:13:02.199539+03
8	auth	0004_alter_user_username_opts	2025-11-20 01:13:02.213887+03
9	auth	0005_alter_user_last_login_null	2025-11-20 01:13:02.228552+03
10	auth	0006_require_contenttypes_0002	2025-11-20 01:13:02.232599+03
11	auth	0007_alter_validators_add_error_messages	2025-11-20 01:13:02.243521+03
12	auth	0008_alter_user_username_max_length	2025-11-20 01:13:02.255375+03
13	auth	0009_alter_user_last_name_max_length	2025-11-20 01:13:02.281851+03
14	auth	0010_alter_group_name_max_length	2025-11-20 01:13:02.29619+03
15	auth	0011_update_proxy_permissions	2025-11-20 01:13:02.324187+03
16	auth	0012_alter_user_first_name_max_length	2025-11-20 01:13:02.338172+03
25	sessions	0001_initial	2025-11-20 01:13:02.908978+03
27	assessments	0003_alter_assessmentresult_confidence_and_more	2025-12-27 17:59:44.650123+03
34	recommendations	0001_initial	2026-01-09 19:58:16.538923+03
35	users	0001_initial	2026-01-09 19:58:16.620403+03
36	users	0002_alter_studentprofile_grade_level_and_more	2026-01-09 19:58:16.642531+03
37	users	0003_alter_school_options_school_created_at_and_more	2026-01-09 19:58:16.692066+03
38	recommendations	0002_initial	2026-01-09 19:58:16.785332+03
39	admin	0001_initial	2026-01-11 06:56:34.928739+03
40	admin	0002_logentry_remove_auto_add	2026-01-11 06:56:34.963041+03
41	admin	0003_logentry_add_action_flag_choices	2026-01-11 06:56:34.977867+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7rs5ciz9pbnohpk5bfadkeh63h6vgiq8	.eJxVjEEOgjAQRe_StWnaSRnApXvPQIZ2vkVNSSisjHdXEha6_e-9_zKDbGsetqrLMCVzNt6b0-84Snxo2Um6S7nNNs5lXabR7oo9aLXXOenzcrh_B1lq_tYsfRcICa3zEAoQdK5NjMYD0lMEUSugEXABjikwlL0ySxTtGvP-ACPvOPw:1vNCri:wm5VDo7lUmmjWnnKPDA3TKYveU3-b5Y9cfv7HCTCgYA	2025-12-07 19:23:06.114277+03
6wjzt7ffvnfssy9edz0cjxdpjw87o706	.eJxVjMsOgjAUBf-la9NoubTFpXu-oel9WdRAQmFl_HchYaHbMzPnbVJel5LWKnMa2FwNmNPvhpmeMu6AH3m8T5amcZkHtLtiD1ptP7G8bof7d1ByLVvdUadNltZB0wERixP1pBBCEIhMkQE3iu4MKm1QRI_Rq4scHFy8ms8XCgA4tg:1vMnHO:dJ4XRbGuJbyOHpdeTiGOmApdOInenuo8pMDH-LYstus	2025-12-06 16:03:54.730358+03
z1rflmjmol94ttnj9ozg1igjtjckoptv	.eJxVjMsOwiAURP-FtSEtApe6dO83kPsAqRqalHZl_HfbpAvdTeacmbeKuC4lri3NcRR1Ub06_XaE_Ex1B_LAep80T3WZR9K7og_a9G2S9Loe7t9BwVa2tREGcAYCO-cBIRlyYL2QBGSfuQfrBmMtE3S5s8nCwCnkfN5iIM7q8wXbezgi:1vZ6JP:Y01ghP6HmWO61C17YrRsSIkhKLukAWwYUCzSK_YVR7M	2026-01-09 14:48:51.16051+03
85rolsxde9du10anbdlyutvq4j5yjme5	.eJxVjMEOwiAQRP-FsyEUAqUevfsNZHdZ2mpDE2gPxvjv0qQHPc7Mm_cWAfZtCnvlEuYorqIXl98OgZ6cjyE-II-rpDVvZUZ5IPJcq7yvkZfbyf4JJqhTe3NCw4n84BUSdK5jVh167XqVLPZ2UFo7B2ZQPlkyCq0zRKSjYSDN0KQLQ8lzHkPdXgs3Z2GILYvPF2xdQf8:1vZUAj:LgdRHFnoHwfLfR90oNsWkVILzvsqH4-QoJL_4gP-WAE	2026-01-10 16:17:29.121397+03
2bta1ba18te9tt6rif68isfbrs2sfsxt	.eJxVjMsOwiAURP-FtSEtApe6dO83kPsAqRqalHZl_HfbpAvdTeacmbeKuC4lri3NcRR1Ub06_XaE_Ex1B_LAep80T3WZR9K7og_a9G2S9Loe7t9BwVa2tREGcAYCO-cBIRlyYL2QBGSfuQfrBmMtE3S5s8nCwCnkfN5iIM7q8wXbezgi:1vYiMY:onEIF67v9l-QWDKgWJ9Vlb9VvSlB5t02UYTMhZ_uUPs	2026-01-08 13:14:30.778304+03
kgmqrtum6lg9zvt3us3pxa8t3phrwhss	.eJxVjMsOwiAQRf-FtSFDgQFcuvcbyPCSqoGktCvjv2uTLnR7zzn3xTxta_XbyIufEzszx06_W6D4yG0H6U7t1nnsbV3mwHeFH3Twa0_5eTncv4NKo35rDRSTUKBECiFL7QiyK0WCAdQWoxUqICgUQkzWGRMsIkYJzkxoyRX2_gDKizaQ:1vMpKF:ZBS09mFNR2TxfD2kMYhxxYErjx-bP2rcBf9NHHSxItI	2025-12-06 18:14:59.565456+03
8uhalxfwhpjjbotfjizs1k6glqy2o5ot	.eJxVjEEOwiAQRe_C2hCxA0xduvcMBGYGqRpISrsy3l2bdKHb_977LxXiupSwdpnDxOqsrDr8binSQ-oG-B7rrWlqdZmnpDdF77Tra2N5Xnb376DEXr51Ju8cEnsYGYgkEluCgZzhkyGPEREyDmiMA-uTOAc5-3y04EEQR_X-APqRN9U:1vMnff:lZoghdiAn3YAFUfA7yh6giUDY3_sbf-gH8GCISkdbhw	2025-12-06 16:28:59.029224+03
2ym1e89cdh7s5s1s4dgxh7a0za3k70su	.eJxVjMEOwiAQBf-FsyHgAgsevfcbCLAgVQNJaU_Gf9cmPej1zcx7MR-2tfpt5MXPxC7MstPvFkN65LYDuod26zz1ti5z5LvCDzr41Ck_r4f7d1DDqN9agJIkFTgQSaVsMQSUyuRy1lopR6QloBbR2gQGMRZjZTFauGIKIQJ7fwC5sjbP:1vMomL:75vRutz-FpWNpPIajqjhhvAFh8eoZDdjDEfAos1R3Iw	2025-12-06 17:39:57.794602+03
ep9d7mcydei5kgq8kjz8sgkzmgrbpxc1	.eJxVjEEOwiAQRe_C2pABh1BcuvcMZBgGqRqalHbVeHdt0oVu_3vvbyrSutS4dpnjmNVFmbM6_Y6J-CltJ_lB7T5pntoyj0nvij5o17cpy-t6uH8HlXr91sw4AGUPZKWwBEJ0AcmxYC5sDHlwCN6aIRhMVhKmHIC5ADowTtT7Ax6GOEg:1vYgOz:od_a8IbhW6xK2j9iHu9VcBm98AMF9HvWmFzpbWh0lWE	2026-01-08 11:08:53.107467+03
4p0yixx1zl6t9whuqejwlwev56wwvd9t	e30:1vb4Hf:gVVVgo-lwtygKlpo3AEih1pASBo5nrvUrsQwABcGKdA	2026-01-15 01:03:11.60568+03
dc6dzlghpd5hmx23a7fibsufduxhasfi	e30:1vb4Jx:Kn-osnIMBstczkHebJSQChIUpStSi04C58wt52pqziM	2026-01-15 01:05:33.528152+03
1mh7v6di8r80vakc29wdhpw33qox3p5g	.eJxVjMEOwiAQRP-FsyFQYAWP3vsNZJdFqRpISnsy_rtt0oNmbvPezFtEXJcS157nOLG4CBCn344wPXPdAT-w3ptMrS7zRHJX5EG7HBvn1_Vw_w4K9rKtvfaaCDhQpkCWElkFDCrc9BayTqFGSH4w6AKaDNZRCmzdOZOBwYnPF_vPOC8:1vMnpW:m39XPyaNz_qs54Ul5knKyxRfoFZdG5UVzvVeooCwvHo	2025-12-06 16:39:10.282019+03
tyixvi8bzayk5rkl9t3n8d0xkqf2s3ep	e30:1vbK5E:Y9aacWiHwJq2S9KpIEt1pU8LoQGTofhMvIPdwzib2_Y	2026-01-15 17:55:24.935162+03
ejknqpsv237ya0d0bz06jgra1wd20fx8	.eJxVjMEOwiAQRP-FsyGWlgY8evcbyLK7FLShCbSHxvjv0qQHPc7Mm_cWDrY1uq1ycYnETXRGXH5LD_jifCz0hDwtEpe8luTlgchzrfKxEM_3k_0TRKixvRVYVFfSQZsRgS3aYBVrZTCMSApCCMYPvVUDgMaewWscuCM7Ym-IuElnhpJTnlxd95mbszBQy-LzBc2lQ0M:1vZPPW:u5oWPAIUuSdt3ieepED1VSqxIvNXJgb7RKkpt1Bqdy4	2026-01-10 11:12:26.414974+03
1g2a6ti1ahiuue23chh2gvztjjy7c55y	.eJxVjDsOwjAQBe_iGln-bbAp6TlDtN5dcADZUpxUiLtDpBTQvpl5LzXiupRx7TKPE6uTsurwu2Wkh9QN8B3rrWlqdZmnrDdF77TrS2N5nnf376BgL9_6St4IG2-ydwNQMmFIViiSpRiAgHJgmyikY0SMPmYBZAdiA4GjFNT7A9-fN84:1veH4D:tiimugY4X3I_YS-SQb9qGt07G6mzILsIOPvj0EzABis	2026-01-23 21:18:33.272815+03
kv8ce31f4efnhvsgnohwk8ycyht6p0gc	.eJxVjEEOwiAQRe_C2pAyFEpcuvcMZGYYpGogKe3KeHdt0oVu_3vvv1TEbS1x67LEOamzMk6dfkdCfkjdSbpjvTXNra7LTHpX9EG7vrYkz8vh_h0U7OVbO8DkrUEywZoABBLYO8bJjWwlSTCWOPkBgLLnTBkmRAsBhMcBnVXvDw9dOHY:1vYiVA:IE-lyMHsDsYIo4AZAOmuellmxz3vgnsbYA48VCHNjNk	2026-01-08 13:23:24.868722+03
8a8m1dtezl6k0p4wngcjq71m6ihspgwi	.eJxVjEEOwiAQRe_C2hAoIMWl-56BzDCDVA0kpV0Z765NutDtf-_9l4iwrSVunZc4k7gII06_G0J6cN0B3aHemkytrsuMclfkQbucGvHzerh_BwV6-daDShycTzqzRoOMVqkAI4xoHAdKnFVG5SFjOOuANntKmoLOjr3FAcX7AwwxOSA:1vMpPx:j7Rrf_jj6aN4PtjKlPDEajY0xY3zm738kTH3UElb4ic	2025-12-06 18:20:53.253172+03
bdc9loidubv7h6crhf3wzwqq8wbokpi2	.eJxVjDsOwjAQBe_iGllerz8xJX3OYK1_OIAcKU4qxN1JpBTQvpl5b-ZpW6vfel78lNiVgWKX3zFQfOZ2kPSgdp95nNu6TIEfCj9p5-Oc8ut2un8HlXrda1MUWCAtTC5BaRktoYuYNBRBKAigIMiCg7QuoIwGdxygSAdk5KDZ5wvx2Dcu:1vYhYC:X-uB0SYJcbl6uV-IsM5qdSimGRMAQ5ih6fb-ZW8SXtM	2026-01-08 12:22:28.022192+03
9pefae6gq3388kzrfkfon2mp3avr6yvj	.eJxVjDEOwjAMRe-SGUVxEreEkZ0zVHbskgJKpaadEHdHlTrA-t97_20G2tYybE2XYRJzMeDM6Xdkyk-tO5EH1fts81zXZWK7K_agzd5m0df1cP8OCrWy1yOhTxJ6HzL0lM4EfXAZEaVDRvUkDkfm6JQ1dZ1CUOAYMINATMl8vgcLN_g:1vMpWU:sRtcNCRO6nVNf8a8cWk57M1LJFb9Ww1T2X6A_DNzwsc	2025-12-06 18:27:38.941168+03
\.


--
-- Data for Name: recommendations_career; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_career (id, name, description, category, average_salary, job_outlook, kenyan_market_demand) FROM stdin;
\.


--
-- Data for Name: recommendations_career_recommended_subjects; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_career_recommended_subjects (id, career_id, subject_id) FROM stdin;
\.


--
-- Data for Name: recommendations_career_required_subjects; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_career_required_subjects (id, career_id, subject_id) FROM stdin;
\.


--
-- Data for Name: recommendations_careerpersonalitymatch; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_careerpersonalitymatch (id, compatibility_score, reasoning, career_id, personality_type_id) FROM stdin;
\.


--
-- Data for Name: recommendations_learningstyle; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_learningstyle (id, name, description, study_recommendations) FROM stdin;
\.


--
-- Data for Name: recommendations_learningstyle_personality_types; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_learningstyle_personality_types (id, learningstyle_id, personalitytype_id) FROM stdin;
\.


--
-- Data for Name: recommendations_studentrecommendation; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_studentrecommendation (id, personality_match_score, academic_match_score, overall_score, reasoning, created_at, career_id, student_id) FROM stdin;
\.


--
-- Data for Name: recommendations_studentrecommendation_recommended_subjects; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_studentrecommendation_recommended_subjects (id, studentrecommendation_id, subject_id) FROM stdin;
\.


--
-- Data for Name: recommendations_subject; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.recommendations_subject (id, name, code, category, difficulty_level) FROM stdin;
\.


--
-- Data for Name: users_customuser; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.users_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, user_type, phone_number, date_of_birth, created_at, updated_at) FROM stdin;
1	pbkdf2_sha256$1000000$MZQH23p6Prm86SKdugn8ji$1kBF0z1GAbzGde44s29ttFrTJjq4LDOs2+1N5DdqN2M=	2026-01-09 21:18:33.264701+03	f	s1gm9	R1ck	Bos	admin@gmail.com	f	t	2026-01-09 21:17:28.784836+03	student		\N	2026-01-09 21:17:29.419926+03	2026-01-09 21:17:29.419939+03
\.


--
-- Data for Name: users_customuser_groups; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.users_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.users_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: users_school; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.users_school (id, name, code, county, type, created_at) FROM stdin;
1	Not Specified	000000	Nairobi	private	2026-01-09 21:17:29.453776+03
\.


--
-- Data for Name: users_studentprofile; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.users_studentprofile (id, grade_level, career_aspirations, kcpe_score, kcse_score, school_id, user_id, created_at, updated_at) FROM stdin;
1			\N		\N	1	2026-01-09 21:17:29.438655+03	2026-01-09 21:18:33.268999+03
\.


--
-- Data for Name: users_studentprofile_subjects; Type: TABLE DATA; Schema: public; Owner: careeratlas_user
--

COPY public.users_studentprofile_subjects (id, studentprofile_id, subject_id) FROM stdin;
\.


--
-- Name: assessments_answerchoice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.assessments_answerchoice_id_seq', 260, true);


--
-- Name: assessments_assessmentresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.assessments_assessmentresult_id_seq', 15, true);


--
-- Name: assessments_assessmentsession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.assessments_assessmentsession_id_seq', 25, true);


--
-- Name: assessments_mbtidimension_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.assessments_mbtidimension_id_seq', 4, true);


--
-- Name: assessments_personalitytype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.assessments_personalitytype_id_seq', 8, true);


--
-- Name: assessments_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.assessments_question_id_seq', 65, true);


--
-- Name: assessments_questionresponse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.assessments_questionresponse_id_seq', 428, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 120, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 30, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 41, true);


--
-- Name: recommendations_career_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_career_id_seq', 1, false);


--
-- Name: recommendations_career_recommended_subjects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_career_recommended_subjects_id_seq', 1, false);


--
-- Name: recommendations_career_required_subjects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_career_required_subjects_id_seq', 1, false);


--
-- Name: recommendations_careerpersonalitymatch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_careerpersonalitymatch_id_seq', 1, false);


--
-- Name: recommendations_learningstyle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_learningstyle_id_seq', 1, false);


--
-- Name: recommendations_learningstyle_personality_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_learningstyle_personality_types_id_seq', 1, false);


--
-- Name: recommendations_studentrecommendation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_studentrecommendation_id_seq', 1, false);


--
-- Name: recommendations_studentrecommendation_recommended_subjec_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_studentrecommendation_recommended_subjec_id_seq', 1, false);


--
-- Name: recommendations_subject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.recommendations_subject_id_seq', 1, false);


--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.users_customuser_groups_id_seq', 1, false);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.users_customuser_id_seq', 1, true);


--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.users_customuser_user_permissions_id_seq', 1, false);


--
-- Name: users_school_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.users_school_id_seq', 1, true);


--
-- Name: users_studentprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.users_studentprofile_id_seq', 2, true);


--
-- Name: users_studentprofile_subjects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: careeratlas_user
--

SELECT pg_catalog.setval('public.users_studentprofile_subjects_id_seq', 1, false);


--
-- Name: assessments_answerchoice assessments_answerchoice_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_answerchoice
    ADD CONSTRAINT assessments_answerchoice_pkey PRIMARY KEY (id);


--
-- Name: assessments_assessmentresult assessments_assessmentresult_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_assessmentresult
    ADD CONSTRAINT assessments_assessmentresult_pkey PRIMARY KEY (id);


--
-- Name: assessments_assessmentsession assessments_assessmentsession_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_assessmentsession
    ADD CONSTRAINT assessments_assessmentsession_pkey PRIMARY KEY (id);


--
-- Name: assessments_mbtidimension assessments_mbtidimension_code_key; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_mbtidimension
    ADD CONSTRAINT assessments_mbtidimension_code_key UNIQUE (code);


--
-- Name: assessments_mbtidimension assessments_mbtidimension_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_mbtidimension
    ADD CONSTRAINT assessments_mbtidimension_pkey PRIMARY KEY (id);


--
-- Name: assessments_personalitytype assessments_personalitytype_mbti_type_key; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_personalitytype
    ADD CONSTRAINT assessments_personalitytype_mbti_type_key UNIQUE (mbti_type);


--
-- Name: assessments_personalitytype assessments_personalitytype_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_personalitytype
    ADD CONSTRAINT assessments_personalitytype_pkey PRIMARY KEY (id);


--
-- Name: assessments_question assessments_question_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_question
    ADD CONSTRAINT assessments_question_pkey PRIMARY KEY (id);


--
-- Name: assessments_questionresponse assessments_questionresponse_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.assessments_questionresponse
    ADD CONSTRAINT assessments_questionresponse_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: recommendations_career recommendations_career_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career
    ADD CONSTRAINT recommendations_career_pkey PRIMARY KEY (id);


--
-- Name: recommendations_career_required_subjects recommendations_career_r_career_id_subject_id_05f89c6d_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_required_subjects
    ADD CONSTRAINT recommendations_career_r_career_id_subject_id_05f89c6d_uniq UNIQUE (career_id, subject_id);


--
-- Name: recommendations_career_recommended_subjects recommendations_career_r_career_id_subject_id_fc0e5752_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_recommended_subjects
    ADD CONSTRAINT recommendations_career_r_career_id_subject_id_fc0e5752_uniq UNIQUE (career_id, subject_id);


--
-- Name: recommendations_career_recommended_subjects recommendations_career_recommended_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_recommended_subjects
    ADD CONSTRAINT recommendations_career_recommended_subjects_pkey PRIMARY KEY (id);


--
-- Name: recommendations_career_required_subjects recommendations_career_required_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_required_subjects
    ADD CONSTRAINT recommendations_career_required_subjects_pkey PRIMARY KEY (id);


--
-- Name: recommendations_careerpersonalitymatch recommendations_careerpe_career_id_personality_ty_5ecc8a16_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_careerpersonalitymatch
    ADD CONSTRAINT recommendations_careerpe_career_id_personality_ty_5ecc8a16_uniq UNIQUE (career_id, personality_type_id);


--
-- Name: recommendations_careerpersonalitymatch recommendations_careerpersonalitymatch_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_careerpersonalitymatch
    ADD CONSTRAINT recommendations_careerpersonalitymatch_pkey PRIMARY KEY (id);


--
-- Name: recommendations_learningstyle_personality_types recommendations_learning_learningstyle_id_persona_91918acf_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_learningstyle_personality_types
    ADD CONSTRAINT recommendations_learning_learningstyle_id_persona_91918acf_uniq UNIQUE (learningstyle_id, personalitytype_id);


--
-- Name: recommendations_learningstyle_personality_types recommendations_learningstyle_personality_types_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_learningstyle_personality_types
    ADD CONSTRAINT recommendations_learningstyle_personality_types_pkey PRIMARY KEY (id);


--
-- Name: recommendations_learningstyle recommendations_learningstyle_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_learningstyle
    ADD CONSTRAINT recommendations_learningstyle_pkey PRIMARY KEY (id);


--
-- Name: recommendations_studentrecommendation recommendations_studentr_student_id_career_id_a4433949_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation
    ADD CONSTRAINT recommendations_studentr_student_id_career_id_a4433949_uniq UNIQUE (student_id, career_id);


--
-- Name: recommendations_studentrecommendation_recommended_subjects recommendations_studentr_studentrecommendation_id_412125ba_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation_recommended_subjects
    ADD CONSTRAINT recommendations_studentr_studentrecommendation_id_412125ba_uniq UNIQUE (studentrecommendation_id, subject_id);


--
-- Name: recommendations_studentrecommendation recommendations_studentrecommendation_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation
    ADD CONSTRAINT recommendations_studentrecommendation_pkey PRIMARY KEY (id);


--
-- Name: recommendations_studentrecommendation_recommended_subjects recommendations_studentrecommendation_recommended_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation_recommended_subjects
    ADD CONSTRAINT recommendations_studentrecommendation_recommended_subjects_pkey PRIMARY KEY (id);


--
-- Name: recommendations_subject recommendations_subject_code_key; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_subject
    ADD CONSTRAINT recommendations_subject_code_key UNIQUE (code);


--
-- Name: recommendations_subject recommendations_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_subject
    ADD CONSTRAINT recommendations_subject_pkey PRIMARY KEY (id);


--
-- Name: users_customuser_groups users_customuser_groups_customuser_id_group_id_76b619e3_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (customuser_id, group_id);


--
-- Name: users_customuser_groups users_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);


--
-- Name: users_customuser_user_permissions users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: users_customuser_user_permissions users_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_username_key UNIQUE (username);


--
-- Name: users_school users_school_code_key; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_school
    ADD CONSTRAINT users_school_code_key UNIQUE (code);


--
-- Name: users_school users_school_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_school
    ADD CONSTRAINT users_school_pkey PRIMARY KEY (id);


--
-- Name: users_studentprofile users_studentprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile
    ADD CONSTRAINT users_studentprofile_pkey PRIMARY KEY (id);


--
-- Name: users_studentprofile_subjects users_studentprofile_sub_studentprofile_id_subjec_9046fceb_uniq; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile_subjects
    ADD CONSTRAINT users_studentprofile_sub_studentprofile_id_subjec_9046fceb_uniq UNIQUE (studentprofile_id, subject_id);


--
-- Name: users_studentprofile_subjects users_studentprofile_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile_subjects
    ADD CONSTRAINT users_studentprofile_subjects_pkey PRIMARY KEY (id);


--
-- Name: users_studentprofile users_studentprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile
    ADD CONSTRAINT users_studentprofile_user_id_key UNIQUE (user_id);


--
-- Name: assessments_mbtidimension_code_40ea6651_like; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX assessments_mbtidimension_code_40ea6651_like ON public.assessments_mbtidimension USING btree (code varchar_pattern_ops);


--
-- Name: assessments_personalitytype_mbti_type_4dfb1a12_like; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX assessments_personalitytype_mbti_type_4dfb1a12_like ON public.assessments_personalitytype USING btree (mbti_type varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: recommendations_career_recommended_subjects_career_id_8c5ec8ab; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_career_recommended_subjects_career_id_8c5ec8ab ON public.recommendations_career_recommended_subjects USING btree (career_id);


--
-- Name: recommendations_career_recommended_subjects_subject_id_b92f60fe; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_career_recommended_subjects_subject_id_b92f60fe ON public.recommendations_career_recommended_subjects USING btree (subject_id);


--
-- Name: recommendations_career_required_subjects_career_id_831f2ccc; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_career_required_subjects_career_id_831f2ccc ON public.recommendations_career_required_subjects USING btree (career_id);


--
-- Name: recommendations_career_required_subjects_subject_id_a764b7e9; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_career_required_subjects_subject_id_a764b7e9 ON public.recommendations_career_required_subjects USING btree (subject_id);


--
-- Name: recommendations_careerpers_personality_type_id_c1cdd690; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_careerpers_personality_type_id_c1cdd690 ON public.recommendations_careerpersonalitymatch USING btree (personality_type_id);


--
-- Name: recommendations_careerpersonalitymatch_career_id_b4ea5696; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_careerpersonalitymatch_career_id_b4ea5696 ON public.recommendations_careerpersonalitymatch USING btree (career_id);


--
-- Name: recommendations_learningst_learningstyle_id_4906bc31; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_learningst_learningstyle_id_4906bc31 ON public.recommendations_learningstyle_personality_types USING btree (learningstyle_id);


--
-- Name: recommendations_learningst_personalitytype_id_fb37f19f; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_learningst_personalitytype_id_fb37f19f ON public.recommendations_learningstyle_personality_types USING btree (personalitytype_id);


--
-- Name: recommendations_studentrec_studentrecommendation_id_d885256c; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_studentrec_studentrecommendation_id_d885256c ON public.recommendations_studentrecommendation_recommended_subjects USING btree (studentrecommendation_id);


--
-- Name: recommendations_studentrec_subject_id_dbac3543; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_studentrec_subject_id_dbac3543 ON public.recommendations_studentrecommendation_recommended_subjects USING btree (subject_id);


--
-- Name: recommendations_studentrecommendation_career_id_e1786b46; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_studentrecommendation_career_id_e1786b46 ON public.recommendations_studentrecommendation USING btree (career_id);


--
-- Name: recommendations_studentrecommendation_student_id_d7d05ab2; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_studentrecommendation_student_id_d7d05ab2 ON public.recommendations_studentrecommendation USING btree (student_id);


--
-- Name: recommendations_subject_code_8b91d3c8_like; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX recommendations_subject_code_8b91d3c8_like ON public.recommendations_subject USING btree (code varchar_pattern_ops);


--
-- Name: users_customuser_groups_customuser_id_958147bf; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_customuser_groups_customuser_id_958147bf ON public.users_customuser_groups USING btree (customuser_id);


--
-- Name: users_customuser_groups_group_id_01390b14; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_customuser_groups_group_id_01390b14 ON public.users_customuser_groups USING btree (group_id);


--
-- Name: users_customuser_user_permissions_customuser_id_5771478b; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_customuser_user_permissions_customuser_id_5771478b ON public.users_customuser_user_permissions USING btree (customuser_id);


--
-- Name: users_customuser_user_permissions_permission_id_baaa2f74; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_customuser_user_permissions_permission_id_baaa2f74 ON public.users_customuser_user_permissions USING btree (permission_id);


--
-- Name: users_customuser_username_80452fdf_like; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_customuser_username_80452fdf_like ON public.users_customuser USING btree (username varchar_pattern_ops);


--
-- Name: users_school_code_a80feae0_like; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_school_code_a80feae0_like ON public.users_school USING btree (code varchar_pattern_ops);


--
-- Name: users_studentprofile_school_id_c3e3730b; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_studentprofile_school_id_c3e3730b ON public.users_studentprofile USING btree (school_id);


--
-- Name: users_studentprofile_subjects_studentprofile_id_8bd0e91a; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_studentprofile_subjects_studentprofile_id_8bd0e91a ON public.users_studentprofile_subjects USING btree (studentprofile_id);


--
-- Name: users_studentprofile_subjects_subject_id_4bc8e8a4; Type: INDEX; Schema: public; Owner: careeratlas_user
--

CREATE INDEX users_studentprofile_subjects_subject_id_4bc8e8a4 ON public.users_studentprofile_subjects USING btree (subject_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_career_required_subjects recommendations_care_career_id_831f2ccc_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_required_subjects
    ADD CONSTRAINT recommendations_care_career_id_831f2ccc_fk_recommend FOREIGN KEY (career_id) REFERENCES public.recommendations_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_career_recommended_subjects recommendations_care_career_id_8c5ec8ab_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_recommended_subjects
    ADD CONSTRAINT recommendations_care_career_id_8c5ec8ab_fk_recommend FOREIGN KEY (career_id) REFERENCES public.recommendations_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_careerpersonalitymatch recommendations_care_career_id_b4ea5696_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_careerpersonalitymatch
    ADD CONSTRAINT recommendations_care_career_id_b4ea5696_fk_recommend FOREIGN KEY (career_id) REFERENCES public.recommendations_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_careerpersonalitymatch recommendations_care_personality_type_id_c1cdd690_fk_assessmen; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_careerpersonalitymatch
    ADD CONSTRAINT recommendations_care_personality_type_id_c1cdd690_fk_assessmen FOREIGN KEY (personality_type_id) REFERENCES public.assessments_personalitytype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_career_required_subjects recommendations_care_subject_id_a764b7e9_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_required_subjects
    ADD CONSTRAINT recommendations_care_subject_id_a764b7e9_fk_recommend FOREIGN KEY (subject_id) REFERENCES public.recommendations_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_career_recommended_subjects recommendations_care_subject_id_b92f60fe_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_career_recommended_subjects
    ADD CONSTRAINT recommendations_care_subject_id_b92f60fe_fk_recommend FOREIGN KEY (subject_id) REFERENCES public.recommendations_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_learningstyle_personality_types recommendations_lear_learningstyle_id_4906bc31_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_learningstyle_personality_types
    ADD CONSTRAINT recommendations_lear_learningstyle_id_4906bc31_fk_recommend FOREIGN KEY (learningstyle_id) REFERENCES public.recommendations_learningstyle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_learningstyle_personality_types recommendations_lear_personalitytype_id_fb37f19f_fk_assessmen; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_learningstyle_personality_types
    ADD CONSTRAINT recommendations_lear_personalitytype_id_fb37f19f_fk_assessmen FOREIGN KEY (personalitytype_id) REFERENCES public.assessments_personalitytype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_studentrecommendation recommendations_stud_career_id_e1786b46_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation
    ADD CONSTRAINT recommendations_stud_career_id_e1786b46_fk_recommend FOREIGN KEY (career_id) REFERENCES public.recommendations_career(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_studentrecommendation recommendations_stud_student_id_d7d05ab2_fk_users_stu; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation
    ADD CONSTRAINT recommendations_stud_student_id_d7d05ab2_fk_users_stu FOREIGN KEY (student_id) REFERENCES public.users_studentprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_studentrecommendation_recommended_subjects recommendations_stud_studentrecommendatio_d885256c_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation_recommended_subjects
    ADD CONSTRAINT recommendations_stud_studentrecommendatio_d885256c_fk_recommend FOREIGN KEY (studentrecommendation_id) REFERENCES public.recommendations_studentrecommendation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recommendations_studentrecommendation_recommended_subjects recommendations_stud_subject_id_dbac3543_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.recommendations_studentrecommendation_recommended_subjects
    ADD CONSTRAINT recommendations_stud_subject_id_dbac3543_fk_recommend FOREIGN KEY (subject_id) REFERENCES public.recommendations_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_gro_customuser_id_958147bf_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_gro_customuser_id_958147bf_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_groups_group_id_01390b14_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_customuser_id_5771478b_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_customuser_id_5771478b_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_permission_id_baaa2f74_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_studentprofile users_studentprofile_school_id_c3e3730b_fk_users_school_id; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile
    ADD CONSTRAINT users_studentprofile_school_id_c3e3730b_fk_users_school_id FOREIGN KEY (school_id) REFERENCES public.users_school(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_studentprofile_subjects users_studentprofile_studentprofile_id_8bd0e91a_fk_users_stu; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile_subjects
    ADD CONSTRAINT users_studentprofile_studentprofile_id_8bd0e91a_fk_users_stu FOREIGN KEY (studentprofile_id) REFERENCES public.users_studentprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_studentprofile_subjects users_studentprofile_subject_id_4bc8e8a4_fk_recommend; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile_subjects
    ADD CONSTRAINT users_studentprofile_subject_id_4bc8e8a4_fk_recommend FOREIGN KEY (subject_id) REFERENCES public.recommendations_subject(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_studentprofile users_studentprofile_user_id_d0e95184_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: careeratlas_user
--

ALTER TABLE ONLY public.users_studentprofile
    ADD CONSTRAINT users_studentprofile_user_id_d0e95184_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO careeratlas_user;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO careeratlas_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO careeratlas_user;


--
-- PostgreSQL database dump complete
--

\unrestrict KtgNhHej0QunVRxf5r3JuD4HYlXKjQ6td0dXZISBZKfXPh25Efp4EfmZckbeONK

