# Generated by Django 6.0.1 on 2026-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ei_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sn_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tf_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jp_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MBTIDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EI', 'Extraversion vs Introversion'), ('SN', 'Sensing vs Intuition'), ('TF', 'Thinking vs Feeling'), ('JP', 'Judging vs Perceiving')], max_length=2, unique=True)),
                ('dimension_a', models.CharField(max_length=50)),
                ('dimension_b', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('career_recommendations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('EI', 'Extraversion/Introversion'), ('SN', 'Sensing/Intuition'), ('TF', 'Thinking/Feeling'), ('JP', 'Judging/Perceiving')], max_length=2)),
                ('dimension_a_weight', models.IntegerField(default=0)),
                ('dimension_b_weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.IntegerField(default=0)),
            ],
        ),
    ]
