# Generated by Django 6.0.1 on 2026-04-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_fix_assessmentresult_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dimension_a_weight',
            field=models.IntegerField(default=1),
        ),
    ]
