# Generated by Django 6.0.1 on 2026-01-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Short description for cards and lists', max_length=300)),
                ('category', models.CharField(choices=[('stem', 'STEM'), ('arts', 'Arts & Humanities'), ('business', 'Business & Commerce'), ('health', 'Health Sciences'), ('education', 'Education'), ('technical', 'Technical & Vocational'), ('engineering', 'Engineering'), ('technology', 'Technology'), ('research', 'Research & Development'), ('public_service', 'Public Service'), ('law', 'Law & Justice'), ('media', 'Media & Communication'), ('agriculture', 'Agriculture'), ('tourism', 'Tourism & Hospitality')], max_length=100)),
                ('subcategory', models.CharField(blank=True, help_text='More specific category e.g., Software Engineering, Pediatrics', max_length=100)),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entry_level_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mid_level_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('senior_level_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kenyan_market_demand', models.CharField(choices=[('very_high', 'Very High Demand'), ('high', 'High Demand'), ('medium', 'Medium Demand'), ('low', 'Low Demand'), ('very_low', 'Very Low Demand')], default='medium', max_length=50)),
                ('market_demand_trend', models.CharField(choices=[('growing', 'Growing'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=50)),
                ('growth_projection', models.CharField(blank=True, help_text='e.g., 30% growth in next 5 years', max_length=200)),
                ('education_requirements', models.TextField(blank=True)),
                ('minimum_education', models.CharField(blank=True, help_text="e.g., KCSE C+, Diploma, Bachelor's", max_length=100)),
                ('skills_required', models.TextField(blank=True, help_text='Comma-separated list of required skills')),
                ('certifications', models.TextField(blank=True, help_text='Required certifications in Kenya')),
                ('work_environment', models.TextField(blank=True)),
                ('typical_work_hours', models.CharField(blank=True, max_length=100)),
                ('career_path', models.TextField(blank=True, help_text='Typical career progression path')),
                ('kenyan_market_analysis', models.TextField(blank=True)),
                ('top_employers', models.TextField(blank=True, help_text='Top employers in Kenya for this career')),
                ('kenyan_universities', models.TextField(blank=True, help_text='Universities offering relevant programs in Kenya')),
                ('scholarships_available', models.TextField(blank=True, help_text='Scholarship opportunities for Kenyan students')),
                ('complexity_level', models.CharField(choices=[('very_high', 'Very High Complexity'), ('high', 'High Complexity'), ('medium', 'Medium Complexity'), ('low', 'Low Complexity')], default='medium', max_length=50)),
                ('learning_duration', models.CharField(blank=True, help_text="e.g., 4 years for Bachelor's", max_length=100)),
                ('is_kenyan_focused', models.BooleanField(default=True, help_text='Is this career particularly relevant to Kenya?')),
                ('recommendation_count', models.IntegerField(default=0, help_text='Number of times recommended')),
                ('interest_count', models.IntegerField(default=0, help_text='Number of students interested')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic'), ('multimodal', 'Multimodal')], max_length=50)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True, help_text='More detailed explanation')),
                ('preferred_activities', models.TextField(blank=True, help_text='Preferred learning activities')),
                ('study_techniques', models.TextField(blank=True, help_text='Effective study techniques')),
                ('common_challenges', models.TextField(blank=True, help_text='Common learning challenges')),
                ('suitable_careers', models.TextField(blank=True, help_text='Careers that match this learning style')),
                ('kenyan_adaptations', models.TextField(blank=True, help_text='How to adapt this style in Kenyan context')),
                ('local_resources', models.TextField(blank=True, help_text='Local resources for this learning style')),
                ('study_recommendations', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recommendations', models.IntegerField(default=0)),
                ('recommendations_viewed', models.IntegerField(default=0)),
                ('recommendations_interested', models.IntegerField(default=0)),
                ('average_compatibility_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('compatibility_distribution', models.JSONField(default=dict, help_text='Distribution by compatibility level')),
                ('category_distribution', models.JSONField(default=dict, help_text='Distribution by career category')),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('generation_count', models.IntegerField(default=0)),
                ('average_generation_time', models.DecimalField(decimal_places=2, default=0.0, help_text='Average generation time in seconds', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Recommendation Analytics',
            },
        ),
        migrations.CreateModel(
            name='StudentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall compatibility score 0.00-1.00', max_digits=3)),
                ('personality_match_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('academic_match_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('market_demand_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('learning_style_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('interests_boost', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('grade_boost', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('reasoning', models.TextField()),
                ('detailed_analysis', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of scoring factors')),
                ('strengths_alignment', models.TextField(blank=True, help_text='How career aligns with student strengths')),
                ('improvement_areas', models.TextField(blank=True, help_text='Areas needing improvement')),
                ('is_interested', models.BooleanField(default=False, help_text='Student expressed interest')),
                ('is_bookmarked', models.BooleanField(default=False, help_text='Student saved for later')),
                ('interest_level', models.IntegerField(default=0, help_text='Interest level 1-10')),
                ('viewed_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('skill_gaps', models.JSONField(blank=True, default=list, help_text='Identified skill gaps')),
                ('learning_path', models.JSONField(blank=True, default=list, help_text='Suggested learning path')),
                ('is_active', models.BooleanField(default=True)),
                ('is_generated', models.BooleanField(default=True, help_text='Was this generated by the system?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('sciences', 'Sciences'), ('humanities', 'Humanities'), ('languages', 'Languages'), ('technical', 'Technical'), ('business', 'Business'), ('mathematics', 'Mathematics'), ('arts', 'Arts'), ('computer', 'Computer Studies'), ('agriculture', 'Agriculture'), ('religious', 'Religious Education')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('kcse_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in KCSE calculation', max_digits=3)),
                ('is_compulsory', models.BooleanField(default=False, help_text='Is this a compulsory subject?')),
                ('minimum_grade', models.CharField(blank=True, help_text='Minimum grade for university consideration', max_length=2)),
                ('career_count', models.IntegerField(default=0, help_text='Number of careers requiring this subject')),
                ('recommended_learning_style', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic'), ('mixed', 'Mixed')], default='mixed', max_length=50)),
                ('study_hours_recommended', models.IntegerField(default=5, help_text='Recommended study hours per week')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPersonalityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, help_text='0.00-1.00 compatibility score', max_digits=3)),
                ('trait_alignment', models.JSONField(default=dict, help_text='Specific MBTI trait alignments')),
                ('reasoning', models.TextField()),
                ('strengths_match', models.TextField(blank=True, help_text='How career matches personality strengths')),
                ('challenges', models.TextField(blank=True, help_text='Potential challenges for this personality')),
                ('is_top_match', models.BooleanField(default=False, help_text='Is this a top match for this personality?')),
                ('popularity_rank', models.IntegerField(default=0, help_text='Popularity rank for this personality type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.career')),
                ('personality_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.personalitytype')),
            ],
            options={
                'ordering': ['personality_type', '-match_score'],
            },
        ),
        migrations.CreateModel(
            name='CareerSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('beneficial', 'Beneficial'), ('optional', 'Optional')], default='recommended', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in academic match calculation', max_digits=3)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.career')),
            ],
            options={
                'ordering': ['career', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='CareerLearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, help_text='0.00-1.00 compatibility score', max_digits=3)),
                ('reasoning', models.TextField()),
                ('learning_requirements', models.TextField(blank=True, help_text='How this career requires this learning style')),
                ('adaptation_tips', models.TextField(blank=True, help_text="Tips for adapting if learning style doesn't match")),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.career')),
                ('learning_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.learningstyle')),
            ],
            options={
                'ordering': ['career', '-match_score'],
            },
        ),
    ]
