# Generated by Django 6.0.1 on 2026-01-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationanalytics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentrecommendation',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.career'),
        ),
        migrations.AddField(
            model_name='studentrecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='high_demand_careers',
            field=models.ManyToManyField(blank=True, related_name='high_demand_subjects', to='recommendations.career'),
        ),
        migrations.AddField(
            model_name='studentrecommendation',
            name='recommended_subjects',
            field=models.ManyToManyField(blank=True, to='recommendations.subject'),
        ),
        migrations.AddField(
            model_name='careersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='beneficial_subjects',
            field=models.ManyToManyField(blank=True, related_name='careers_beneficial', to='recommendations.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='recommended_subjects',
            field=models.ManyToManyField(related_name='careers_recommending', to='recommendations.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='required_subjects',
            field=models.ManyToManyField(related_name='careers_requiring', to='recommendations.subject'),
        ),
        migrations.AddIndex(
            model_name='careerpersonalitymatch',
            index=models.Index(fields=['personality_type', 'match_score'], name='recommendat_persona_1dee99_idx'),
        ),
        migrations.AddIndex(
            model_name='careerpersonalitymatch',
            index=models.Index(fields=['is_top_match'], name='recommendat_is_top__2ef23e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='careerpersonalitymatch',
            unique_together={('career', 'personality_type')},
        ),
        migrations.AlterUniqueTogether(
            name='careerlearningstyle',
            unique_together={('career', 'learning_style')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category'], name='recommendat_categor_49b373_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['difficulty_level'], name='recommendat_difficu_363151_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_compulsory'], name='recommendat_is_comp_fb36c3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecommendation',
            index=models.Index(fields=['student', 'overall_score'], name='recommendat_student_d494c6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecommendation',
            index=models.Index(fields=['student', 'is_interested'], name='recommendat_student_49071a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecommendation',
            index=models.Index(fields=['student', 'created_at'], name='recommendat_student_e24f9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentrecommendation',
            unique_together={('student', 'career')},
        ),
        migrations.AlterUniqueTogether(
            name='careersubject',
            unique_together={('career', 'subject')},
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['category'], name='recommendat_categor_8f50b4_idx'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['kenyan_market_demand'], name='recommendat_kenyan__ed360d_idx'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['average_salary'], name='recommendat_average_aeee8b_idx'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['is_active'], name='recommendat_is_acti_b28018_idx'),
        ),
    ]
