"""
Populate CareerCompass Kenya with 200+ careers across all major fields.
Run: python manage.py populate_careers
"""
from django.core.management.base import BaseCommand
from recommendations.models import Career


# Maps the freetext Title-Case values used in the CAREERS list below to the
# canonical lowercase keys defined in Career.CATEGORY_CHOICES.  Any value not
# in this map is lowercased and stored as-is (which is still more consistent
# than the original Title-Case).
_CAT_NORMALISE = {
    'Agriculture':    'agriculture',
    'Business':       'business',
    'Construction':   'construction',
    'Creative Arts':  'arts',
    'Education':      'education',
    'Engineering':    'engineering',
    'Environment':    'environment',
    'Finance':        'business',        # Finance maps to Business & Commerce
    'Healthcare':     'health',
    'Hospitality':    'tourism',         # Tourism & Hospitality
    'Law':            'law',
    'Mathematics':    'stem',
    'Media':          'media',
    'NGO':            'public_service',
    'Science':        'stem',
    'Security':       'technical',
    'Social Sciences':'education',
    'Sports':         'arts',
    'Technology':     'technology',
    'Tourism':        'tourism',
    'Transport':      'technical',
}


class Command(BaseCommand):
    help = 'Populate 200+ careers into CareerCompass Kenya database'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Loading careers...'))

        # Step 1 — normalise any existing careers that still have Title-Case categories
        normalised = 0
        for raw, canonical in _CAT_NORMALISE.items():
            updated = Career.objects.filter(category=raw).update(category=canonical)
            normalised += updated
        if normalised:
            self.stdout.write(self.style.WARNING(
                f'  Normalised {normalised} existing career categories to lowercase keys.'
            ))

        # Step 2 — upsert careers from the list below
        count = 0
        for c in CAREERS:
            raw_cat = c.get('category', 'technology')
            category = _CAT_NORMALISE.get(raw_cat, raw_cat.lower())
            _, created = Career.objects.update_or_create(
                name=c['name'],
                defaults={
                    'description':            c.get('description', ''),
                    'category':               category,
                    'kenyan_market_demand':   c.get('demand', 'medium'),
                    'average_salary':         c.get('salary') or c.get('mid'),
                    'entry_level_salary':     c.get('entry'),
                    'mid_level_salary':       c.get('mid'),
                    'senior_level_salary':    c.get('senior'),
                    'education_requirements': c.get('education', ''),
                    'skills_required':        c.get('skills', ''),
                    'growth_projection':      c.get('growth', ''),
                    'is_active':              True,
                }
            )
            if created:
                count += 1
        self.stdout.write(self.style.SUCCESS(
            f'Done. {count} new careers added. Total: {Career.objects.count()}'
        ))



CAREERS = [
    {'name': 'Software Developer', 'category': 'Technology', 'demand': 'very_high', 'entry': 80000, 'mid': 140000, 'senior': 250000, 'salary': 140000, 'description': 'Design and build software applications.', 'education': "Bachelor's in Computer Science", 'skills': 'Programming, Problem Solving', 'growth': '35%'},
    {'name': 'Data Scientist', 'category': 'Technology', 'demand': 'very_high', 'entry': 90000, 'mid': 160000, 'senior': 280000, 'salary': 160000, 'description': 'Analyze complex datasets to drive decisions.', 'education': "Bachelor's/Master's in Data Science", 'skills': 'Python, Statistics, ML', 'growth': '40%'},
    {'name': 'Cybersecurity Analyst', 'category': 'Technology', 'demand': 'very_high', 'entry': 85000, 'mid': 150000, 'senior': 260000, 'salary': 150000, 'description': 'Protect systems from cyber threats.', 'education': "Bachelor's in IT Security", 'skills': 'Network Security, Ethical Hacking', 'growth': '38%'},
    {'name': 'Cloud Engineer', 'category': 'Technology', 'demand': 'very_high', 'entry': 90000, 'mid': 165000, 'senior': 280000, 'salary': 165000, 'description': 'Build and manage cloud infrastructure.', 'education': "Bachelor's in CS/IT", 'skills': 'AWS, Azure, DevOps', 'growth': '42%'},
    {'name': 'Machine Learning Engineer', 'category': 'Technology', 'demand': 'very_high', 'entry': 95000, 'mid': 175000, 'senior': 300000, 'salary': 175000, 'description': 'Build AI/ML models and systems.', 'education': "Master's in CS or Data Science", 'skills': 'Python, TensorFlow, Statistics', 'growth': '45%'},
    {'name': 'DevOps Engineer', 'category': 'Technology', 'demand': 'high', 'entry': 85000, 'mid': 155000, 'senior': 260000, 'salary': 155000, 'description': 'Bridge development and operations.', 'education': "Bachelor's in CS/IT", 'skills': 'CI/CD, Docker, Kubernetes', 'growth': '32%'},
    {'name': 'Mobile App Developer', 'category': 'Technology', 'demand': 'high', 'entry': 75000, 'mid': 130000, 'senior': 220000, 'salary': 130000, 'description': 'Build iOS and Android applications.', 'education': "Bachelor's in CS", 'skills': 'React Native, Flutter, Swift', 'growth': '30%'},
    {'name': 'UI/UX Designer', 'category': 'Technology', 'demand': 'high', 'entry': 70000, 'mid': 120000, 'senior': 200000, 'salary': 120000, 'description': 'Design user interfaces and experiences.', 'education': "Bachelor's in Design or HCI", 'skills': 'Figma, Adobe XD, User Research', 'growth': '28%'},
    {'name': 'Database Administrator', 'category': 'Technology', 'demand': 'high', 'entry': 75000, 'mid': 130000, 'senior': 210000, 'salary': 130000, 'description': 'Manage and optimize databases.', 'education': "Bachelor's in CS/IT", 'skills': 'SQL, PostgreSQL, MongoDB', 'growth': '20%'},
    {'name': 'Full Stack Developer', 'category': 'Technology', 'demand': 'very_high', 'entry': 78000, 'mid': 138000, 'senior': 230000, 'salary': 138000, 'description': 'Build both front-end and back-end systems.', 'education': "Bachelor's in CS", 'skills': 'JavaScript, React, Node.js', 'growth': '33%'},
    {'name': 'Penetration Tester', 'category': 'Technology', 'demand': 'very_high', 'entry': 85000, 'mid': 155000, 'senior': 270000, 'salary': 155000, 'description': 'Test systems for security vulnerabilities.', 'education': "Bachelor's CS/IT + CEH/OSCP", 'skills': 'Ethical Hacking, Security Tools', 'growth': '40%'},
    {'name': 'Data Analyst', 'category': 'Technology', 'demand': 'very_high', 'entry': 65000, 'mid': 115000, 'senior': 195000, 'salary': 115000, 'description': 'Analyze data to support business decisions.', 'education': 'BSc Statistics or CS', 'skills': 'SQL, Excel, Python', 'growth': '32%'},
    {'name': 'Product Manager', 'category': 'Technology', 'demand': 'high', 'entry': 80000, 'mid': 145000, 'senior': 250000, 'salary': 145000, 'description': 'Lead product development and strategy.', 'education': 'BCom/CS + product training', 'skills': 'Product Strategy, Agile', 'growth': '30%'},
    {'name': 'Web Developer', 'category': 'Technology', 'demand': 'very_high', 'entry': 60000, 'mid': 108000, 'senior': 185000, 'salary': 108000, 'description': 'Build and maintain websites.', 'education': 'Diploma/BSc CS', 'skills': 'HTML, CSS, JavaScript', 'growth': '25%'},
    {'name': 'Network Engineer', 'category': 'Technology', 'demand': 'high', 'entry': 72000, 'mid': 125000, 'senior': 200000, 'salary': 125000, 'description': 'Design and manage computer networks.', 'education': "Bachelor's in Networking", 'skills': 'CCNA, TCP/IP, Firewalls', 'growth': '18%'},
    {'name': 'IT Project Manager', 'category': 'Technology', 'demand': 'high', 'entry': 80000, 'mid': 140000, 'senior': 230000, 'salary': 140000, 'description': 'Lead technology projects.', 'education': "Bachelor's + PMP certification", 'skills': 'Project Management, Agile', 'growth': '22%'},
    {'name': 'Blockchain Developer', 'category': 'Technology', 'demand': 'medium', 'entry': 90000, 'mid': 165000, 'senior': 280000, 'salary': 165000, 'description': 'Build decentralized applications.', 'education': "Bachelor's in CS", 'skills': 'Solidity, Ethereum, Web3', 'growth': '50%'},
    {'name': 'Game Developer', 'category': 'Technology', 'demand': 'medium', 'entry': 65000, 'mid': 115000, 'senior': 190000, 'salary': 115000, 'description': 'Design and build video games.', 'education': "Bachelor's in CS or Game Design", 'skills': 'Unity, Unreal, C#', 'growth': '22%'},
    {'name': 'Computer Vision Engineer', 'category': 'Technology', 'demand': 'high', 'entry': 95000, 'mid': 170000, 'senior': 290000, 'salary': 170000, 'description': 'Build systems that interpret visual data.', 'education': "Master's in CS/AI", 'skills': 'OpenCV, Python, Deep Learning', 'growth': '48%'},
    {'name': 'Solutions Architect', 'category': 'Technology', 'demand': 'high', 'entry': 100000, 'mid': 180000, 'senior': 300000, 'salary': 180000, 'description': 'Design complex software and system solutions.', 'education': 'BSc CS + architecture experience', 'skills': 'System Design, Cloud', 'growth': '28%'},
    {'name': 'Medical Doctor', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 120000, 'mid': 200000, 'senior': 350000, 'salary': 200000, 'description': 'Diagnose and treat illnesses.', 'education': 'MBChB (6 years)', 'skills': 'Diagnosis, Patient Care', 'growth': '25%'},
    {'name': 'Surgeon', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 200000, 'mid': 350000, 'senior': 600000, 'salary': 350000, 'description': 'Perform surgical operations.', 'education': 'MBChB + Surgery (10+ years)', 'skills': 'Surgery, Precision', 'growth': '22%'},
    {'name': 'Registered Nurse', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 55000, 'mid': 85000, 'senior': 140000, 'salary': 85000, 'description': 'Provide patient care and medical support.', 'education': 'BSc Nursing or Diploma', 'skills': 'Patient Care, Clinical Skills', 'growth': '30%'},
    {'name': 'Pharmacist', 'category': 'Healthcare', 'demand': 'high', 'entry': 80000, 'mid': 130000, 'senior': 210000, 'salary': 130000, 'description': 'Dispense medications and advise on therapy.', 'education': 'Bachelor of Pharmacy (5 years)', 'skills': 'Pharmacology, Drug Interaction', 'growth': '18%'},
    {'name': 'Dentist', 'category': 'Healthcare', 'demand': 'high', 'entry': 90000, 'mid': 160000, 'senior': 280000, 'salary': 160000, 'description': 'Diagnose and treat oral health problems.', 'education': 'Bachelor of Dental Surgery (5 years)', 'skills': 'Dental Procedures, Patient Care', 'growth': '20%'},
    {'name': 'Clinical Psychologist', 'category': 'Healthcare', 'demand': 'high', 'entry': 70000, 'mid': 115000, 'senior': 185000, 'salary': 115000, 'description': 'Assess and treat mental health conditions.', 'education': "Master's/PhD in Psychology", 'skills': 'Psychotherapy, Assessment', 'growth': '32%'},
    {'name': 'Physiotherapist', 'category': 'Healthcare', 'demand': 'high', 'entry': 65000, 'mid': 100000, 'senior': 160000, 'salary': 100000, 'description': 'Help patients recover physical function.', 'education': 'Bachelor of Physiotherapy', 'skills': 'Rehabilitation, Exercise Therapy', 'growth': '25%'},
    {'name': 'Radiologist', 'category': 'Healthcare', 'demand': 'high', 'entry': 150000, 'mid': 250000, 'senior': 420000, 'salary': 250000, 'description': 'Interpret medical images for diagnosis.', 'education': 'MBChB + Radiology (12 years)', 'skills': 'Image Interpretation, Anatomy', 'growth': '28%'},
    {'name': 'Psychiatrist', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 130000, 'mid': 220000, 'senior': 380000, 'salary': 220000, 'description': 'Diagnose and treat mental disorders.', 'education': 'MBChB + Psychiatry', 'skills': 'Mental Health, Therapy', 'growth': '35%'},
    {'name': 'Public Health Officer', 'category': 'Healthcare', 'demand': 'high', 'entry': 55000, 'mid': 90000, 'senior': 145000, 'salary': 90000, 'description': 'Promote community health and prevent disease.', 'education': 'BSc Public Health', 'skills': 'Epidemiology, Health Promotion', 'growth': '25%'},
    {'name': 'Biomedical Engineer', 'category': 'Healthcare', 'demand': 'high', 'entry': 75000, 'mid': 130000, 'senior': 210000, 'salary': 130000, 'description': 'Develop medical devices and equipment.', 'education': 'BSc Biomedical Engineering', 'skills': 'Engineering, Biology, Electronics', 'growth': '30%'},
    {'name': 'Anesthesiologist', 'category': 'Healthcare', 'demand': 'high', 'entry': 180000, 'mid': 300000, 'senior': 500000, 'salary': 300000, 'description': 'Administer anesthesia during surgery.', 'education': 'MBChB + Anesthesiology (12 years)', 'skills': 'Pharmacology, Critical Care', 'growth': '20%'},
    {'name': 'Oncologist', 'category': 'Healthcare', 'demand': 'high', 'entry': 160000, 'mid': 280000, 'senior': 460000, 'salary': 280000, 'description': 'Diagnose and treat cancer.', 'education': 'MBChB + Oncology (12+ years)', 'skills': 'Cancer Treatment, Chemotherapy', 'growth': '28%'},
    {'name': 'Pediatrician', 'category': 'Healthcare', 'demand': 'high', 'entry': 130000, 'mid': 220000, 'senior': 370000, 'salary': 220000, 'description': 'Provide medical care for children.', 'education': 'MBChB + Pediatrics (10+ years)', 'skills': 'Child Health, Development', 'growth': '22%'},
    {'name': 'Nutritionist', 'category': 'Healthcare', 'demand': 'medium', 'entry': 50000, 'mid': 80000, 'senior': 130000, 'salary': 80000, 'description': 'Advise on diet and nutrition.', 'education': 'BSc Nutrition and Dietetics', 'skills': 'Nutrition Science, Counseling', 'growth': '20%'},
    {'name': 'Medical Laboratory Scientist', 'category': 'Healthcare', 'demand': 'high', 'entry': 55000, 'mid': 90000, 'senior': 145000, 'salary': 90000, 'description': 'Analyze biological samples for diagnosis.', 'education': 'BSc Medical Laboratory Science', 'skills': 'Lab Techniques, Analysis', 'growth': '22%'},
    {'name': 'Mental Health Counselor', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 55000, 'mid': 90000, 'senior': 148000, 'salary': 90000, 'description': 'Provide mental health support.', 'education': "Master's in Counseling or Psychology", 'skills': 'Counseling, CBT, Empathy', 'growth': '35%'},
    {'name': 'Community Health Worker', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 30000, 'mid': 50000, 'senior': 80000, 'salary': 50000, 'description': 'Promote health in communities.', 'education': 'Certificate in Community Health', 'skills': 'Community Engagement', 'growth': '25%'},
    {'name': 'Civil Engineer', 'category': 'Engineering', 'demand': 'very_high', 'entry': 75000, 'mid': 130000, 'senior': 220000, 'salary': 130000, 'description': 'Design and build infrastructure.', 'education': 'BSc Civil Engineering', 'skills': 'Structural Analysis, AutoCAD', 'growth': '28%'},
    {'name': 'Electrical Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 78000, 'mid': 135000, 'senior': 225000, 'salary': 135000, 'description': 'Design electrical systems and equipment.', 'education': 'BSc Electrical Engineering', 'skills': 'Circuit Design, Power Systems', 'growth': '22%'},
    {'name': 'Mechanical Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 75000, 'mid': 130000, 'senior': 215000, 'salary': 130000, 'description': 'Design and build mechanical systems.', 'education': 'BSc Mechanical Engineering', 'skills': 'CAD, Thermodynamics', 'growth': '20%'},
    {'name': 'Chemical Engineer', 'category': 'Engineering', 'demand': 'medium', 'entry': 80000, 'mid': 140000, 'senior': 230000, 'salary': 140000, 'description': 'Design chemical manufacturing processes.', 'education': 'BSc Chemical Engineering', 'skills': 'Process Design, Chemistry', 'growth': '18%'},
    {'name': 'Environmental Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 72000, 'mid': 120000, 'senior': 195000, 'salary': 120000, 'description': 'Solve environmental problems using engineering.', 'education': 'BSc Environmental Engineering', 'skills': 'Environmental Science, Modeling', 'growth': '30%'},
    {'name': 'Petroleum Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 100000, 'mid': 180000, 'senior': 320000, 'salary': 180000, 'description': 'Extract oil and gas from the earth.', 'education': 'BSc Petroleum Engineering', 'skills': 'Reservoir Engineering, Drilling', 'growth': '15%'},
    {'name': 'Renewable Energy Engineer', 'category': 'Engineering', 'demand': 'very_high', 'entry': 80000, 'mid': 140000, 'senior': 235000, 'salary': 140000, 'description': 'Design solar, wind, and renewable systems.', 'education': 'BSc Electrical/Renewable Energy', 'skills': 'Solar PV, Wind, Grid Systems', 'growth': '45%'},
    {'name': 'Telecommunications Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 80000, 'mid': 138000, 'senior': 228000, 'salary': 138000, 'description': 'Design and maintain communication networks.', 'education': 'BSc Telecommunications', 'skills': 'RF Engineering, Fiber Optics', 'growth': '22%'},
    {'name': 'Mining Engineer', 'category': 'Engineering', 'demand': 'medium', 'entry': 85000, 'mid': 148000, 'senior': 250000, 'salary': 148000, 'description': 'Plan and operate mines for mineral extraction.', 'education': 'BSc Mining Engineering', 'skills': 'Geology, Mine Planning, Safety', 'growth': '15%'},
    {'name': 'Water Resources Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 72000, 'mid': 120000, 'senior': 195000, 'salary': 120000, 'description': 'Manage water supply and irrigation systems.', 'education': 'BSc Civil/Water Engineering', 'skills': 'Hydrology, Hydraulics', 'growth': '28%'},
    {'name': 'Accountant', 'category': 'Finance', 'demand': 'very_high', 'entry': 55000, 'mid': 95000, 'senior': 165000, 'salary': 95000, 'description': 'Prepare and analyze financial records.', 'education': 'BCom Accounting + CPA', 'skills': 'Accounting, Taxation, Excel', 'growth': '18%'},
    {'name': 'Financial Analyst', 'category': 'Finance', 'demand': 'high', 'entry': 70000, 'mid': 120000, 'senior': 200000, 'salary': 120000, 'description': 'Analyze financial data to guide investments.', 'education': 'BCom Finance or Economics', 'skills': 'Financial Modeling, Analysis', 'growth': '22%'},
    {'name': 'Actuary', 'category': 'Finance', 'demand': 'high', 'entry': 90000, 'mid': 160000, 'senior': 280000, 'salary': 160000, 'description': 'Assess financial risk using mathematics.', 'education': 'BSc Actuarial Science', 'skills': 'Statistics, Risk, Excel', 'growth': '25%'},
    {'name': 'Investment Banker', 'category': 'Finance', 'demand': 'medium', 'entry': 90000, 'mid': 180000, 'senior': 400000, 'salary': 180000, 'description': 'Advise on mergers, acquisitions, and capital.', 'education': 'BCom Finance + MBA', 'skills': 'Financial Modeling, Negotiation', 'growth': '15%'},
    {'name': 'Auditor', 'category': 'Finance', 'demand': 'high', 'entry': 55000, 'mid': 95000, 'senior': 160000, 'salary': 95000, 'description': 'Examine financial statements for accuracy.', 'education': 'BCom Accounting + CPA', 'skills': 'Audit, Compliance', 'growth': '18%'},
    {'name': 'Business Analyst', 'category': 'Business', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Analyze business processes and requirements.', 'education': 'BCom Business or IT', 'skills': 'Analysis, Requirements, SQL', 'growth': '22%'},
    {'name': 'Marketing Manager', 'category': 'Business', 'demand': 'high', 'entry': 65000, 'mid': 115000, 'senior': 190000, 'salary': 115000, 'description': 'Develop and execute marketing strategies.', 'education': 'BCom Marketing or Business', 'skills': 'Marketing, Digital, Analytics', 'growth': '20%'},
    {'name': 'Human Resources Manager', 'category': 'Business', 'demand': 'high', 'entry': 60000, 'mid': 100000, 'senior': 165000, 'salary': 100000, 'description': 'Manage recruitment and employee relations.', 'education': 'BCom HR or Business', 'skills': 'HR Management, Communication', 'growth': '18%'},
    {'name': 'Supply Chain Manager', 'category': 'Business', 'demand': 'high', 'entry': 70000, 'mid': 120000, 'senior': 200000, 'salary': 120000, 'description': 'Oversee procurement and distribution.', 'education': 'BCom Supply Chain or Logistics', 'skills': 'Logistics, Procurement, ERP', 'growth': '22%'},
    {'name': 'Digital Marketing Specialist', 'category': 'Media', 'demand': 'very_high', 'entry': 55000, 'mid': 95000, 'senior': 160000, 'salary': 95000, 'description': 'Manage online marketing campaigns.', 'education': 'BCom Marketing or Communications', 'skills': 'SEO, SEM, Social Media', 'growth': '35%'},
    {'name': 'Management Consultant', 'category': 'Business', 'demand': 'medium', 'entry': 80000, 'mid': 150000, 'senior': 300000, 'salary': 150000, 'description': 'Advise organizations on performance.', 'education': 'BCom/MBA', 'skills': 'Strategy, Analysis, Presentation', 'growth': '18%'},
    {'name': 'Operations Manager', 'category': 'Business', 'demand': 'high', 'entry': 75000, 'mid': 130000, 'senior': 215000, 'salary': 130000, 'description': 'Oversee daily business operations.', 'education': 'BCom Business or MBA', 'skills': 'Operations, Leadership', 'growth': '20%'},
    {'name': 'Entrepreneur', 'category': 'Business', 'demand': 'very_high', 'entry': 0, 'mid': 0, 'senior': 0, 'salary': 0, 'description': 'Start and run your own business.', 'education': 'Any field + business acumen', 'skills': 'Leadership, Risk-taking, Innovation', 'growth': 'N/A'},
    {'name': 'Compliance Officer', 'category': 'Finance', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Ensure organizations follow laws and regulations.', 'education': 'Degree in Law, Finance, or Business', 'skills': 'Regulatory Knowledge, Risk', 'growth': '22%'},
    {'name': 'Secondary School Teacher', 'category': 'Education', 'demand': 'very_high', 'entry': 40000, 'mid': 65000, 'senior': 100000, 'salary': 65000, 'description': 'Teach students in secondary school.', 'education': 'BEd or Degree + PGDE', 'skills': 'Teaching, Subject Knowledge, Patience', 'growth': '15%'},
    {'name': 'Primary School Teacher', 'category': 'Education', 'demand': 'very_high', 'entry': 35000, 'mid': 55000, 'senior': 85000, 'salary': 55000, 'description': 'Educate children in primary school.', 'education': 'BEd Primary Education', 'skills': 'Child Development, Teaching', 'growth': '12%'},
    {'name': 'University Lecturer', 'category': 'Education', 'demand': 'high', 'entry': 80000, 'mid': 140000, 'senior': 240000, 'salary': 140000, 'description': 'Teach and research at university level.', 'education': "Master's or PhD", 'skills': 'Research, Teaching, Publication', 'growth': '18%'},
    {'name': 'Special Needs Educator', 'category': 'Education', 'demand': 'high', 'entry': 40000, 'mid': 65000, 'senior': 105000, 'salary': 65000, 'description': 'Teach students with learning disabilities.', 'education': 'BEd Special Education', 'skills': 'Special Education, Patience', 'growth': '22%'},
    {'name': 'E-Learning Developer', 'category': 'Education', 'demand': 'high', 'entry': 60000, 'mid': 100000, 'senior': 165000, 'salary': 100000, 'description': 'Create online educational content.', 'education': 'Degree in IT or Education', 'skills': 'Instructional Design, LMS, Video', 'growth': '35%'},
    {'name': 'Educational Psychologist', 'category': 'Education', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Support students with learning and mental health.', 'education': "Master's in Educational Psychology", 'skills': 'Psychology, Assessment, Counseling', 'growth': '25%'},
    {'name': 'Advocate (Lawyer)', 'category': 'Law', 'demand': 'high', 'entry': 70000, 'mid': 130000, 'senior': 350000, 'salary': 130000, 'description': 'Represent clients in legal matters.', 'education': 'LLB + Advocate training', 'skills': 'Legal Research, Advocacy, Writing', 'growth': '18%'},
    {'name': 'Corporate Lawyer', 'category': 'Law', 'demand': 'high', 'entry': 80000, 'mid': 160000, 'senior': 400000, 'salary': 160000, 'description': 'Handle legal matters for businesses.', 'education': 'LLB + corporate law specialization', 'skills': 'Contract Law, Negotiations', 'growth': '20%'},
    {'name': 'Legal Officer', 'category': 'Law', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Provide legal advice to organizations.', 'education': 'LLB', 'skills': 'Legal Research, Compliance', 'growth': '18%'},
    {'name': 'Paralegal', 'category': 'Law', 'demand': 'medium', 'entry': 45000, 'mid': 75000, 'senior': 120000, 'salary': 75000, 'description': 'Assist lawyers with legal work.', 'education': 'Diploma or Degree in Paralegal Studies', 'skills': 'Legal Research, Documentation', 'growth': '15%'},
    {'name': 'Environmental Lawyer', 'category': 'Law', 'demand': 'medium', 'entry': 70000, 'mid': 130000, 'senior': 250000, 'salary': 130000, 'description': 'Handle environmental legal matters.', 'education': 'LLB + environmental law', 'skills': 'Environmental Law, Policy', 'growth': '25%'},
    {'name': 'Agronomist', 'category': 'Agriculture', 'demand': 'high', 'entry': 55000, 'mid': 88000, 'senior': 145000, 'salary': 88000, 'description': 'Improve crop production and soil management.', 'education': 'BSc Agriculture (Agronomy)', 'skills': 'Crop Science, Soil Science', 'growth': '20%'},
    {'name': 'Agricultural Extension Officer', 'category': 'Agriculture', 'demand': 'high', 'entry': 45000, 'mid': 72000, 'senior': 115000, 'salary': 72000, 'description': 'Advise farmers on best practices.', 'education': 'BSc Agriculture', 'skills': 'Farming, Communication, Training', 'growth': '18%'},
    {'name': 'Food Scientist', 'category': 'Agriculture', 'demand': 'high', 'entry': 60000, 'mid': 100000, 'senior': 165000, 'salary': 100000, 'description': 'Develop and improve food products.', 'education': 'BSc Food Science & Technology', 'skills': 'Food Processing, Quality Control', 'growth': '22%'},
    {'name': 'Horticulturist', 'category': 'Agriculture', 'demand': 'high', 'entry': 50000, 'mid': 80000, 'senior': 130000, 'salary': 80000, 'description': 'Grow fruits, vegetables, and ornamental plants.', 'education': 'BSc Horticulture', 'skills': 'Plant Science, Crop Management', 'growth': '22%'},
    {'name': 'Environmental Scientist', 'category': 'Environment', 'demand': 'high', 'entry': 60000, 'mid': 100000, 'senior': 165000, 'salary': 100000, 'description': 'Study environmental problems and solutions.', 'education': 'BSc Environmental Science', 'skills': 'Environmental Analysis, Research', 'growth': '28%'},
    {'name': 'Wildlife Conservationist', 'category': 'Environment', 'demand': 'medium', 'entry': 50000, 'mid': 80000, 'senior': 130000, 'salary': 80000, 'description': 'Protect wildlife and natural habitats.', 'education': 'BSc Wildlife Management', 'skills': 'Conservation, Field Research', 'growth': '20%'},
    {'name': 'Climate Change Analyst', 'category': 'Environment', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Analyze and address climate change impacts.', 'education': 'BSc Climate Science', 'skills': 'Climate Modeling, Data Analysis', 'growth': '40%'},
    {'name': 'Journalist', 'category': 'Media', 'demand': 'medium', 'entry': 40000, 'mid': 70000, 'senior': 120000, 'salary': 70000, 'description': 'Report news and stories for media outlets.', 'education': 'BA Journalism or Mass Communication', 'skills': 'Writing, Research, Ethics', 'growth': '10%'},
    {'name': 'Graphic Designer', 'category': 'Media', 'demand': 'high', 'entry': 45000, 'mid': 80000, 'senior': 135000, 'salary': 80000, 'description': 'Create visual content for communication.', 'education': 'Diploma/Degree in Graphic Design', 'skills': 'Adobe Creative Suite, Typography', 'growth': '18%'},
    {'name': 'Content Creator', 'category': 'Media', 'demand': 'very_high', 'entry': 30000, 'mid': 80000, 'senior': 200000, 'salary': 80000, 'description': 'Create engaging digital content.', 'education': 'Any degree + digital skills', 'skills': 'Writing, Video, Photography', 'growth': '50%'},
    {'name': 'Social Media Manager', 'category': 'Media', 'demand': 'very_high', 'entry': 45000, 'mid': 80000, 'senior': 140000, 'salary': 80000, 'description': 'Manage social media presence for organizations.', 'education': 'BA Communications or Marketing', 'skills': 'Social Media, Content, Analytics', 'growth': '40%'},
    {'name': 'Animator', 'category': 'Media', 'demand': 'high', 'entry': 45000, 'mid': 80000, 'senior': 138000, 'salary': 80000, 'description': 'Create animated content for various media.', 'education': 'Diploma/Degree in Animation', 'skills': '3D Animation, Maya, Blender', 'growth': '28%'},
    {'name': 'Video Editor', 'category': 'Media', 'demand': 'high', 'entry': 40000, 'mid': 72000, 'senior': 125000, 'salary': 72000, 'description': 'Edit video footage for productions.', 'education': 'Diploma/Degree in Film or Media', 'skills': 'Adobe Premiere, DaVinci Resolve', 'growth': '25%'},
    {'name': 'Photographer', 'category': 'Media', 'demand': 'medium', 'entry': 35000, 'mid': 70000, 'senior': 150000, 'salary': 70000, 'description': 'Capture images for clients and publications.', 'education': 'Diploma in Photography', 'skills': 'Photography, Editing, Composition', 'growth': '15%'},
    {'name': 'Copywriter', 'category': 'Media', 'demand': 'high', 'entry': 40000, 'mid': 75000, 'senior': 138000, 'salary': 75000, 'description': 'Write persuasive marketing content.', 'education': 'BA English or Communications', 'skills': 'Writing, Creativity, Marketing', 'growth': '22%'},
    {'name': 'Social Worker', 'category': 'Social Sciences', 'demand': 'high', 'entry': 40000, 'mid': 65000, 'senior': 105000, 'salary': 65000, 'description': 'Support vulnerable individuals and communities.', 'education': 'BSc Social Work', 'skills': 'Counseling, Advocacy, Case Management', 'growth': '22%'},
    {'name': 'Community Development Officer', 'category': 'Social Sciences', 'demand': 'high', 'entry': 45000, 'mid': 72000, 'senior': 115000, 'salary': 72000, 'description': 'Facilitate development initiatives.', 'education': 'BSc Community Development', 'skills': 'Project Management, Communication', 'growth': '20%'},
    {'name': 'Counselor/Therapist', 'category': 'Social Sciences', 'demand': 'high', 'entry': 55000, 'mid': 90000, 'senior': 145000, 'salary': 90000, 'description': 'Provide mental health counseling.', 'education': "Master's in Counseling Psychology", 'skills': 'Counseling, Empathy, Ethics', 'growth': '28%'},
    {'name': 'Career Counselor', 'category': 'Social Sciences', 'demand': 'medium', 'entry': 50000, 'mid': 82000, 'senior': 135000, 'salary': 82000, 'description': 'Help individuals make career decisions.', 'education': "Bachelor's in Psychology or Counseling", 'skills': 'Counseling, Career Assessment', 'growth': '22%'},
    {'name': 'NGO Program Manager', 'category': 'NGO', 'demand': 'medium', 'entry': 65000, 'mid': 110000, 'senior': 185000, 'salary': 110000, 'description': 'Manage humanitarian and development programs.', 'education': 'Degree + project management', 'skills': 'Project Management, Proposal Writing', 'growth': '18%'},
    {'name': 'Monitoring & Evaluation Specialist', 'category': 'NGO', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Track and evaluate program outcomes.', 'education': 'Degree + M&E training', 'skills': 'Data Collection, Analysis, Reporting', 'growth': '22%'},
    {'name': 'Research Scientist', 'category': 'Science', 'demand': 'medium', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Conduct scientific research in specialized fields.', 'education': "Master's/PhD in relevant field", 'skills': 'Research Design, Lab Skills', 'growth': '18%'},
    {'name': 'Microbiologist', 'category': 'Science', 'demand': 'high', 'entry': 62000, 'mid': 102000, 'senior': 168000, 'salary': 102000, 'description': 'Study microorganisms and their effects.', 'education': 'BSc Microbiology', 'skills': 'Lab Techniques, Research', 'growth': '20%'},
    {'name': 'Epidemiologist', 'category': 'Science', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Study disease patterns and public health.', 'education': 'MPH Epidemiology', 'skills': 'Statistics, Epidemiology, Research', 'growth': '28%'},
    {'name': 'Statistician', 'category': 'Mathematics', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Collect and analyze statistical data.', 'education': 'BSc Statistics', 'skills': 'Statistics, R/Python, Excel', 'growth': '22%'},
    {'name': 'Geologist', 'category': 'Science', 'demand': 'medium', 'entry': 65000, 'mid': 108000, 'senior': 178000, 'salary': 108000, 'description': "Study Earth's structure and processes.", 'education': 'BSc Geology', 'skills': 'Field Mapping, Mineralogy', 'growth': '15%'},
    {'name': 'Physicist', 'category': 'Science', 'demand': 'low', 'entry': 65000, 'mid': 108000, 'senior': 178000, 'salary': 108000, 'description': 'Study matter, energy, and laws of physics.', 'education': 'BSc/PhD Physics', 'skills': 'Mathematical Modeling, Research', 'growth': '10%'},
    {'name': 'Biochemist', 'category': 'Science', 'demand': 'medium', 'entry': 60000, 'mid': 100000, 'senior': 165000, 'salary': 100000, 'description': 'Study chemical processes in living organisms.', 'education': 'BSc/MSc Biochemistry', 'skills': 'Lab Techniques, Research', 'growth': '15%'},
    {'name': 'Architect', 'category': 'Construction', 'demand': 'high', 'entry': 70000, 'mid': 120000, 'senior': 200000, 'salary': 120000, 'description': 'Design buildings and spaces.', 'education': 'Bachelor of Architecture (5 years)', 'skills': 'AutoCAD, Design, 3D Modeling', 'growth': '22%'},
    {'name': 'Quantity Surveyor', 'category': 'Construction', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Estimate construction costs.', 'education': 'BSc Quantity Surveying', 'skills': 'Cost Estimation, BOQ, Contracts', 'growth': '20%'},
    {'name': 'Urban Planner', 'category': 'Construction', 'demand': 'medium', 'entry': 60000, 'mid': 100000, 'senior': 165000, 'salary': 100000, 'description': 'Plan land use and urban development.', 'education': 'BSc Urban Planning', 'skills': 'GIS, Planning Regulations', 'growth': '18%'},
    {'name': 'Land Surveyor', 'category': 'Construction', 'demand': 'high', 'entry': 60000, 'mid': 100000, 'senior': 165000, 'salary': 100000, 'description': 'Measure and map land boundaries.', 'education': 'BSc Land Surveying', 'skills': 'GPS, GIS, Total Station', 'growth': '18%'},
    {'name': 'Site Engineer', 'category': 'Construction', 'demand': 'high', 'entry': 65000, 'mid': 108000, 'senior': 178000, 'salary': 108000, 'description': 'Oversee construction activities on site.', 'education': 'BSc Civil Engineering', 'skills': 'Construction Management, AutoCAD', 'growth': '22%'},
    {'name': 'Hotel Manager', 'category': 'Hospitality', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 185000, 'salary': 110000, 'description': 'Manage hotel operations and guest experience.', 'education': 'Diploma/Degree in Hospitality', 'skills': 'Hospitality, Leadership, Finance', 'growth': '20%'},
    {'name': 'Chef/Cook', 'category': 'Hospitality', 'demand': 'high', 'entry': 35000, 'mid': 70000, 'senior': 130000, 'salary': 70000, 'description': 'Prepare and cook food in restaurants and hotels.', 'education': 'Certificate/Diploma in Culinary Arts', 'skills': 'Cooking, Food Safety, Creativity', 'growth': '22%'},
    {'name': 'Event Planner', 'category': 'Hospitality', 'demand': 'high', 'entry': 45000, 'mid': 80000, 'senior': 140000, 'salary': 80000, 'description': 'Organize and coordinate events.', 'education': 'Diploma/Degree in Events Management', 'skills': 'Organization, Vendor Management', 'growth': '25%'},
    {'name': 'Tour Guide', 'category': 'Tourism', 'demand': 'medium', 'entry': 30000, 'mid': 60000, 'senior': 100000, 'salary': 60000, 'description': 'Guide tourists at attractions and parks.', 'education': 'Diploma in Tour Guiding', 'skills': 'Communication, Kenya Geography', 'growth': '18%'},
    {'name': 'Travel Agent', 'category': 'Tourism', 'demand': 'medium', 'entry': 35000, 'mid': 65000, 'senior': 110000, 'salary': 65000, 'description': 'Plan and book travel for clients.', 'education': 'Diploma in Travel and Tourism', 'skills': 'Travel Planning, Customer Service', 'growth': '15%'},
    {'name': 'Pilot', 'category': 'Transport', 'demand': 'high', 'entry': 120000, 'mid': 220000, 'senior': 400000, 'salary': 220000, 'description': 'Fly commercial or private aircraft.', 'education': 'Diploma in Aviation + CPL/ATPL', 'skills': 'Flying, Navigation, Safety', 'growth': '20%'},
    {'name': 'Logistics Manager', 'category': 'Transport', 'demand': 'high', 'entry': 65000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Manage transportation and distribution networks.', 'education': 'BCom Logistics or Supply Chain', 'skills': 'Logistics, ERP, Analytics', 'growth': '22%'},
    {'name': 'Maritime Officer', 'category': 'Transport', 'demand': 'medium', 'entry': 70000, 'mid': 120000, 'senior': 200000, 'salary': 120000, 'description': 'Navigate and operate ships.', 'education': 'BSc Maritime Science', 'skills': 'Navigation, Maritime Law', 'growth': '15%'},
    {'name': 'Police Officer', 'category': 'Security', 'demand': 'high', 'entry': 35000, 'mid': 60000, 'senior': 100000, 'salary': 60000, 'description': 'Maintain law and order in communities.', 'education': 'KCSE + National Police Service training', 'skills': 'Law Enforcement, Fitness', 'growth': '10%'},
    {'name': 'Military Officer', 'category': 'Security', 'demand': 'medium', 'entry': 45000, 'mid': 80000, 'senior': 160000, 'salary': 80000, 'description': 'Lead and serve in the Kenya Defence Forces.', 'education': 'KCSE + Military training (KMA)', 'skills': 'Leadership, Physical Fitness', 'growth': '8%'},
    {'name': 'Security Manager', 'category': 'Security', 'demand': 'high', 'entry': 55000, 'mid': 90000, 'senior': 150000, 'salary': 90000, 'description': 'Oversee security operations for organizations.', 'education': 'Degree + Security management training', 'skills': 'Security Management, Risk', 'growth': '18%'},
    {'name': 'Fashion Designer', 'category': 'Creative Arts', 'demand': 'medium', 'entry': 35000, 'mid': 70000, 'senior': 150000, 'salary': 70000, 'description': 'Design clothing and accessories.', 'education': 'Diploma/Degree in Fashion Design', 'skills': 'Design, Sewing, Trend Analysis', 'growth': '15%'},
    {'name': 'Musician', 'category': 'Creative Arts', 'demand': 'medium', 'entry': 20000, 'mid': 80000, 'senior': 300000, 'salary': 80000, 'description': 'Perform, compose, or produce music.', 'education': 'Music training/certification', 'skills': 'Musical Instruments, Composition', 'growth': '10%'},
    {'name': 'Photographer (Commercial)', 'category': 'Creative Arts', 'demand': 'medium', 'entry': 40000, 'mid': 75000, 'senior': 145000, 'salary': 75000, 'description': 'Capture images for commercial clients.', 'education': 'Diploma in Photography + portfolio', 'skills': 'Photography, Editing, Business', 'growth': '18%'},
    {'name': 'Sports Coach', 'category': 'Sports', 'demand': 'medium', 'entry': 40000, 'mid': 70000, 'senior': 120000, 'salary': 70000, 'description': 'Train and develop athletes.', 'education': 'Diploma/Degree in Sports Science', 'skills': 'Coaching, Sports Medicine', 'growth': '18%'},
    {'name': 'Physical Education Teacher', 'category': 'Sports', 'demand': 'high', 'entry': 38000, 'mid': 60000, 'senior': 95000, 'salary': 60000, 'description': 'Teach physical education in schools.', 'education': 'BEd Physical Education', 'skills': 'Teaching, Sports, Fitness', 'growth': '12%'},
    {'name': 'Sports Scientist', 'category': 'Sports', 'demand': 'medium', 'entry': 55000, 'mid': 90000, 'senior': 148000, 'salary': 90000, 'description': 'Apply science to improve athletic performance.', 'education': 'BSc Sports Science', 'skills': 'Exercise Physiology, Biomechanics', 'growth': '20%'},

    # ── Additional Technology ──────────────────────────────────────────────
    {'name': 'Blockchain Developer', 'category': 'Technology', 'demand': 'high', 'entry': 90000, 'mid': 160000, 'senior': 280000, 'salary': 160000, 'description': 'Build decentralised applications on blockchain platforms.', 'education': 'BSc Computer Science', 'skills': 'Solidity, Web3, cryptography, smart contracts', 'growth': '35%'},
    {'name': 'DevOps Engineer', 'category': 'Technology', 'demand': 'high', 'entry': 85000, 'mid': 150000, 'senior': 260000, 'salary': 150000, 'description': 'Manage CI/CD pipelines and cloud infrastructure.', 'education': 'BSc Computer Science', 'skills': 'Docker, Kubernetes, AWS, Linux, CI/CD', 'growth': '28%'},
    {'name': 'Cloud Solutions Architect', 'category': 'Technology', 'demand': 'high', 'entry': 100000, 'mid': 180000, 'senior': 320000, 'salary': 180000, 'description': 'Design cloud infrastructure and migration strategies.', 'education': 'BSc Computer Science + cloud certifications', 'skills': 'AWS, Azure, GCP, networking, security', 'growth': '30%'},
    {'name': 'Game Developer', 'category': 'Technology', 'demand': 'medium', 'entry': 60000, 'mid': 110000, 'senior': 200000, 'salary': 110000, 'description': 'Create video games for mobile, PC, and console platforms.', 'education': 'BSc Computer Science or Game Design', 'skills': 'Unity, Unreal Engine, C++, game physics', 'growth': '20%'},
    {'name': 'UI/UX Designer', 'category': 'Technology', 'demand': 'high', 'entry': 55000, 'mid': 100000, 'senior': 180000, 'salary': 100000, 'description': 'Design user interfaces and digital experiences.', 'education': 'Diploma or BSc in Graphic Design or HCI', 'skills': 'Figma, Adobe XD, user research, prototyping', 'growth': '22%'},
    {'name': 'Artificial Intelligence Engineer', 'category': 'Technology', 'demand': 'very_high', 'entry': 100000, 'mid': 185000, 'senior': 320000, 'salary': 185000, 'description': 'Build intelligent systems using ML and deep learning.', 'education': 'BSc Computer Science; MSc AI preferred', 'skills': 'Python, TensorFlow, PyTorch, NLP, computer vision', 'growth': '40%'},
    {'name': 'Database Administrator', 'category': 'Technology', 'demand': 'high', 'entry': 70000, 'mid': 130000, 'senior': 220000, 'salary': 130000, 'description': 'Manage and optimise organisational databases.', 'education': 'BSc Computer Science', 'skills': 'SQL, Oracle, PostgreSQL, MongoDB', 'growth': '15%'},
    {'name': 'Digital Marketing Specialist', 'category': 'Technology', 'demand': 'high', 'entry': 45000, 'mid': 85000, 'senior': 150000, 'salary': 85000, 'description': 'Drive online brand visibility using SEO, social media, and paid ads.', 'education': 'BSc Marketing or Communications', 'skills': 'SEO, Google Ads, Meta Ads, analytics, content strategy', 'growth': '25%'},
    {'name': 'Mobile Money Developer', 'category': 'Technology', 'demand': 'very_high', 'entry': 90000, 'mid': 160000, 'senior': 280000, 'salary': 160000, 'description': 'Build financial technology applications for M-PESA and mobile banking platforms.', 'education': 'BSc Computer Science', 'skills': 'API integration, mobile development, financial systems, security', 'growth': '40%'},
    {'name': 'GIS Analyst', 'category': 'Technology', 'demand': 'high', 'entry': 55000, 'mid': 100000, 'senior': 170000, 'salary': 100000, 'description': 'Analyse and visualise geographic data for planning, conservation, and development.', 'education': 'BSc Geography or Geomatics', 'skills': 'ArcGIS, QGIS, remote sensing, spatial analysis', 'growth': '20%'},
    {'name': 'Drone Operator / UAV Pilot', 'category': 'Technology', 'demand': 'high', 'entry': 45000, 'mid': 85000, 'senior': 150000, 'salary': 85000, 'description': 'Operate drones for aerial photography, surveys, agriculture, and logistics.', 'education': 'KCAA Drone Pilot Licence', 'skills': 'UAV piloting, photogrammetry, mapping software, safety procedures', 'growth': '35%'},
    {'name': 'Robotics Engineer', 'category': 'Technology', 'demand': 'medium', 'entry': 80000, 'mid': 150000, 'senior': 260000, 'salary': 150000, 'description': 'Design, build, and programme robotic systems.', 'education': 'BSc Mechanical or Electrical Engineering', 'skills': 'ROS, Python, C++, sensors, actuators', 'growth': '25%'},
    {'name': 'Technical Writer', 'category': 'Technology', 'demand': 'medium', 'entry': 45000, 'mid': 80000, 'senior': 140000, 'salary': 80000, 'description': 'Create technical documentation, manuals, and guides.', 'education': 'BSc Technical Communication or Computer Science', 'skills': 'Technical writing, Markdown, API docs, Confluence', 'growth': '12%'},
    # ── Engineering (additional) ──────────────────────────────────────────
    {'name': 'Mechatronics Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 80000, 'mid': 150000, 'senior': 260000, 'salary': 150000, 'description': 'Integrate mechanical, electrical, and computing systems.', 'education': 'BSc Mechatronics Engineering', 'skills': 'PLC, automation, robotics, embedded systems', 'growth': '22%'},
    {'name': 'Petroleum Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 100000, 'mid': 200000, 'senior': 380000, 'salary': 200000, 'description': 'Design systems for extracting oil and gas resources.', 'education': 'BSc Petroleum Engineering', 'skills': 'reservoir engineering, drilling, simulation software', 'growth': '15%'},
    {'name': 'Marine Engineer', 'category': 'Engineering', 'demand': 'medium', 'entry': 80000, 'mid': 150000, 'senior': 260000, 'salary': 150000, 'description': 'Design and maintain ships, offshore platforms, and maritime systems.', 'education': 'BSc Marine Engineering', 'skills': 'naval architecture, propulsion systems, fluid dynamics', 'growth': '12%'},
    {'name': 'Mining Engineer', 'category': 'Engineering', 'demand': 'medium', 'entry': 85000, 'mid': 160000, 'senior': 280000, 'salary': 160000, 'description': 'Plan and manage extraction of minerals and resources.', 'education': 'BSc Mining Engineering', 'skills': 'mine planning, explosives, GIS, safety management', 'growth': '10%'},
    {'name': 'Biomedical Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 80000, 'mid': 150000, 'senior': 260000, 'salary': 150000, 'description': 'Design medical devices, prosthetics, and healthcare technology.', 'education': 'BSc Biomedical Engineering', 'skills': 'medical imaging, biomechanics, regulatory compliance', 'growth': '26%'},
    {'name': 'Water Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 70000, 'mid': 130000, 'senior': 220000, 'salary': 130000, 'description': 'Design water supply, treatment, and irrigation systems for Kenya.', 'education': 'BSc Civil or Water Engineering', 'skills': 'hydraulics, GIS, WASH programming, project management', 'growth': '20%'},
    {'name': 'Renewable Energy Engineer', 'category': 'Engineering', 'demand': 'very_high', 'entry': 80000, 'mid': 150000, 'senior': 270000, 'salary': 150000, 'description': 'Design solar, wind, and geothermal energy systems for Kenya.', 'education': 'BSc Electrical or Renewable Energy Engineering', 'skills': 'solar PV, wind turbines, energy storage, grid integration', 'growth': '35%'},
    {'name': 'Telecommunications Engineer', 'category': 'Engineering', 'demand': 'high', 'entry': 75000, 'mid': 140000, 'senior': 240000, 'salary': 140000, 'description': 'Design and maintain communication networks and infrastructure.', 'education': 'BSc Telecommunications Engineering', 'skills': '5G, fibre optics, RF systems, network planning', 'growth': '20%'},
    {'name': 'Railway Engineer', 'category': 'Engineering', 'demand': 'medium', 'entry': 75000, 'mid': 140000, 'senior': 240000, 'salary': 140000, 'description': 'Design, build, and maintain railway systems including the SGR.', 'education': 'BSc Civil or Mechanical Engineering', 'skills': 'track design, signalling, civil works, maintenance planning', 'growth': '15%'},
    # ── Health (additional) ───────────────────────────────────────────────
    {'name': 'Cardiologist', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 200000, 'mid': 400000, 'senior': 700000, 'salary': 400000, 'description': 'Specialise in diagnosing and treating heart and cardiovascular diseases.', 'education': 'MBChB + Masters in Cardiology', 'skills': 'ECG, echocardiography, catheterisation, pharmacology', 'growth': '20%'},
    {'name': 'Paediatrician', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 180000, 'mid': 360000, 'senior': 620000, 'salary': 360000, 'description': 'Provide medical care for infants, children, and adolescents.', 'education': 'MBChB + Masters in Paediatrics', 'skills': 'child development, immunisation, diagnosis, surgery', 'growth': '18%'},
    {'name': 'Gynaecologist', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 180000, 'mid': 360000, 'senior': 620000, 'salary': 360000, 'description': "Specialise in women's reproductive health and obstetrics.", 'education': 'MBChB + Masters in O&G', 'skills': 'obstetrics, ultrasound, surgical procedures, maternal health', 'growth': '18%'},
    {'name': 'Oncologist', 'category': 'Healthcare', 'demand': 'very_high', 'entry': 200000, 'mid': 420000, 'senior': 720000, 'salary': 420000, 'description': 'Diagnose and treat cancer using chemotherapy, radiation, and surgery.', 'education': 'MBChB + Masters in Oncology', 'skills': 'chemotherapy, radiation therapy, tumour biology', 'growth': '22%'},
    {'name': 'Medical Laboratory Scientist', 'category': 'Healthcare', 'demand': 'high', 'entry': 60000, 'mid': 110000, 'senior': 180000, 'salary': 110000, 'description': 'Conduct laboratory tests to diagnose diseases and monitor treatment.', 'education': 'BSc Medical Laboratory Science', 'skills': 'haematology, microbiology, clinical chemistry, quality control', 'growth': '15%'},
    {'name': 'Mental Health Counsellor', 'category': 'Healthcare', 'demand': 'high', 'entry': 50000, 'mid': 90000, 'senior': 150000, 'salary': 90000, 'description': 'Provide counselling and psychotherapy for mental health conditions.', 'education': 'BA Psychology + Counselling certification', 'skills': 'CBT, psychotherapy, active listening, crisis intervention', 'growth': '25%'},
    {'name': 'Speech Therapist', 'category': 'Healthcare', 'demand': 'high', 'entry': 55000, 'mid': 100000, 'senior': 170000, 'salary': 100000, 'description': 'Assess and treat speech, language, and swallowing disorders.', 'education': 'BSc Speech and Language Therapy', 'skills': 'audiology, language assessment, dysphagia management', 'growth': '18%'},
    {'name': 'Biostatistician', 'category': 'Healthcare', 'demand': 'high', 'entry': 70000, 'mid': 130000, 'senior': 220000, 'salary': 130000, 'description': 'Apply statistical methods to analyse medical and public health data.', 'education': 'BSc Statistics or Mathematics + public health training', 'skills': 'R, STATA, SPSS, clinical trial design, epidemiology', 'growth': '20%'},
    {'name': 'Sports Physiotherapist', 'category': 'Healthcare', 'demand': 'high', 'entry': 60000, 'mid': 110000, 'senior': 190000, 'salary': 110000, 'description': 'Prevent and treat sports injuries for athletes.', 'education': 'BSc Physiotherapy', 'skills': 'injury assessment, rehabilitation, sports medicine, taping', 'growth': '20%'},
    # ── Business (additional) ─────────────────────────────────────────────
    {'name': 'Actuary', 'category': 'Business', 'demand': 'high', 'entry': 90000, 'mid': 170000, 'senior': 300000, 'salary': 170000, 'description': 'Assess financial risk using mathematics, statistics, and financial theory.', 'education': 'BSc Actuarial Science', 'skills': 'risk modelling, statistical analysis, insurance, Excel VBA', 'growth': '18%'},
    {'name': 'Investment Banker', 'category': 'Business', 'demand': 'high', 'entry': 100000, 'mid': 200000, 'senior': 400000, 'salary': 200000, 'description': 'Facilitate large financial transactions, mergers, and capital raising.', 'education': 'BSc Finance or Economics + MBA', 'skills': 'financial modelling, valuation, deal structuring, capital markets', 'growth': '15%'},
    {'name': 'Microfinance Officer', 'category': 'Business', 'demand': 'high', 'entry': 40000, 'mid': 75000, 'senior': 130000, 'salary': 75000, 'description': 'Provide financial services and loans to small businesses and rural communities.', 'education': 'Diploma or BSc in Microfinance or Business', 'skills': 'credit analysis, financial literacy, community mobilisation', 'growth': '18%'},
    {'name': 'Real Estate Developer', 'category': 'Business', 'demand': 'high', 'entry': 80000, 'mid': 160000, 'senior': 350000, 'salary': 160000, 'description': 'Identify, finance, and oversee property development projects in Kenya.', 'education': 'BSc Real Estate or Business', 'skills': 'property valuation, project management, financing, legal', 'growth': '20%'},
    {'name': 'Management Consultant', 'category': 'Business', 'demand': 'high', 'entry': 80000, 'mid': 160000, 'senior': 300000, 'salary': 160000, 'description': 'Help organisations improve performance, strategy, and operations.', 'education': "Bachelor's in Business or Finance; MBA a strong asset", 'skills': 'strategy, problem solving, data analysis, presentations', 'growth': '16%'},
    {'name': 'Brand Manager', 'category': 'Business', 'demand': 'medium', 'entry': 55000, 'mid': 100000, 'senior': 180000, 'salary': 100000, 'description': 'Develop and manage brand identity, positioning, and marketing strategy.', 'education': 'BSc Marketing or Business Administration', 'skills': 'brand strategy, consumer insights, campaign management, analytics', 'growth': '14%'},
    {'name': 'Tax Consultant', 'category': 'Business', 'demand': 'high', 'entry': 60000, 'mid': 110000, 'senior': 190000, 'salary': 110000, 'description': 'Advise businesses and individuals on KRA tax compliance and planning.', 'education': 'BCom Accounting + CPA certification', 'skills': 'KRA iTax, tax law, VAT, PAYE, corporate tax planning', 'growth': '15%'},
    # ── Education (additional) ─────────────────────────────────────────────
    {'name': 'Special Needs Education Teacher', 'category': 'Education', 'demand': 'high', 'entry': 35000, 'mid': 60000, 'senior': 100000, 'salary': 60000, 'description': 'Teach and support learners with physical, cognitive, or learning disabilities.', 'education': 'BEd Special Needs Education', 'skills': 'IEP development, AAC, sign language, Braille, inclusive teaching', 'growth': '20%'},
    {'name': 'Curriculum Developer', 'category': 'Education', 'demand': 'medium', 'entry': 55000, 'mid': 100000, 'senior': 170000, 'salary': 100000, 'description': 'Design learning programmes and educational materials for KICD and schools.', 'education': 'BEd + postgraduate training', 'skills': 'instructional design, assessment, competency-based curriculum, e-learning', 'growth': '12%'},
    {'name': 'Educational Technology Specialist', 'category': 'Education', 'demand': 'high', 'entry': 55000, 'mid': 100000, 'senior': 170000, 'salary': 100000, 'description': 'Integrate digital tools and e-learning into classroom instruction.', 'education': 'BEd + diploma in IT or EdTech', 'skills': 'LMS, Moodle, Google Classroom, instructional design, video production', 'growth': '25%'},
    {'name': 'TVET Instructor', 'category': 'Education', 'demand': 'high', 'entry': 40000, 'mid': 70000, 'senior': 120000, 'salary': 70000, 'description': 'Teach vocational and technical skills at TVET institutions in Kenya.', 'education': 'Diploma or BSc in relevant trade + CPTD', 'skills': 'practical training, competency-based assessment, industry experience', 'growth': '20%'},
    # ── Law (additional) ──────────────────────────────────────────────────
    {'name': 'Corporate Lawyer', 'category': 'Law', 'demand': 'high', 'entry': 90000, 'mid': 190000, 'senior': 420000, 'salary': 190000, 'description': 'Advise businesses on legal matters including contracts, M&A, and compliance.', 'education': 'LLB + Kenya School of Law', 'skills': 'contract law, corporate law, due diligence, negotiation', 'growth': '15%'},
    {'name': 'Compliance Officer', 'category': 'Law', 'demand': 'high', 'entry': 60000, 'mid': 120000, 'senior': 220000, 'salary': 120000, 'description': 'Ensure organisations adhere to regulations, laws, and internal policies.', 'education': 'LLB or BSc Business + compliance certification', 'skills': 'regulatory knowledge, risk assessment, audit, reporting', 'growth': '18%'},
    {'name': 'Land Economist', 'category': 'Law', 'demand': 'high', 'entry': 60000, 'mid': 120000, 'senior': 220000, 'salary': 120000, 'description': 'Value land and property for taxation, sale, and development in Kenya.', 'education': 'BSc Land Economics', 'skills': 'property valuation, GIS, land registration, planning law', 'growth': '18%'},
    # ── Environment & Sustainability ──────────────────────────────────────
    {'name': 'Environmental Consultant', 'category': 'Environment', 'demand': 'high', 'entry': 65000, 'mid': 120000, 'senior': 210000, 'salary': 120000, 'description': 'Conduct Environmental Impact Assessments for development projects in Kenya.', 'education': 'BSc Environmental Science', 'skills': 'EIA, NEMA compliance, GIS, report writing, stakeholder engagement', 'growth': '20%'},
    {'name': 'Climate Change Analyst', 'category': 'Environment', 'demand': 'high', 'entry': 65000, 'mid': 120000, 'senior': 210000, 'salary': 120000, 'description': 'Analyse climate data and develop adaptation strategies for Kenya.', 'education': 'BSc Environmental Science or Geography', 'skills': 'climate modelling, policy analysis, GIS, carbon accounting', 'growth': '28%'},
    {'name': 'Wildlife Biologist', 'category': 'Environment', 'demand': 'medium', 'entry': 55000, 'mid': 100000, 'senior': 170000, 'salary': 100000, 'description': "Study and conserve wildlife populations in Kenya's national parks and reserves.", 'education': 'BSc Wildlife Management or Zoology', 'skills': 'field research, GPS tracking, species identification, conservation planning', 'growth': '14%'},
    {'name': 'Hydrologist', 'category': 'Environment', 'demand': 'medium', 'entry': 60000, 'mid': 110000, 'senior': 190000, 'salary': 110000, 'description': 'Study water movement and availability to support water resource management.', 'education': 'BSc Hydrology or Environmental Science', 'skills': 'hydrological modelling, GIS, water quality analysis, field surveys', 'growth': '18%'},
    {'name': 'Waste Management Specialist', 'category': 'Environment', 'demand': 'high', 'entry': 55000, 'mid': 100000, 'senior': 170000, 'salary': 100000, 'description': 'Design and manage sustainable waste collection, recycling, and disposal systems.', 'education': 'BSc Environmental Engineering', 'skills': 'waste characterisation, recycling, landfill management, circular economy', 'growth': '22%'},
    # ── Media & Creative (additional) ────────────────────────────────────
    {'name': 'Social Media Manager', 'category': 'Media', 'demand': 'high', 'entry': 40000, 'mid': 75000, 'senior': 140000, 'salary': 75000, 'description': 'Manage brand presence and audience engagement across social media platforms.', 'education': 'Diploma or BSc Marketing or Communications', 'skills': 'content creation, scheduling tools, analytics, copywriting, paid ads', 'growth': '25%'},
    {'name': 'Content Creator', 'category': 'Media', 'demand': 'high', 'entry': 30000, 'mid': 70000, 'senior': 150000, 'salary': 70000, 'description': 'Produce YouTube, TikTok, podcast, or blog content as a digital media career.', 'education': 'Self-taught or Diploma in Media Production', 'skills': 'video production, editing, audience building, monetisation, SEO', 'growth': '35%'},
    {'name': 'Translator and Interpreter', 'category': 'Media', 'demand': 'medium', 'entry': 40000, 'mid': 75000, 'senior': 140000, 'salary': 75000, 'description': 'Translate documents and interpret speech across languages for organisations.', 'education': 'BA Languages or Translation Studies', 'skills': 'Kiswahili, English, French, Arabic or other languages, CAT tools', 'growth': '12%'},
    {'name': 'Art Director', 'category': 'Media', 'demand': 'medium', 'entry': 60000, 'mid': 110000, 'senior': 200000, 'salary': 110000, 'description': 'Lead visual design and creative direction for agencies, publishers, or studios.', 'education': 'BA Graphic Design or Fine Art', 'skills': 'Adobe Creative Suite, visual communication, team leadership, branding', 'growth': '14%'},
    {'name': 'Event Manager', 'category': 'Media', 'demand': 'medium', 'entry': 40000, 'mid': 75000, 'senior': 140000, 'salary': 75000, 'description': 'Plan and coordinate conferences, weddings, corporate events, and festivals.', 'education': 'Diploma or BSc Event Management', 'skills': 'logistics, vendor management, budgeting, marketing, client relations', 'growth': '15%'},
    # ── Public Service / NGO ──────────────────────────────────────────────
    {'name': 'Development Worker', 'category': 'NGO', 'demand': 'high', 'entry': 50000, 'mid': 90000, 'senior': 160000, 'salary': 90000, 'description': 'Implement community development programmes for NGOs and government.', 'education': 'BA Community Development or Social Work', 'skills': 'project management, M&E, community mobilisation, grant writing', 'growth': '18%'},
    {'name': 'Gender and Inclusion Specialist', 'category': 'NGO', 'demand': 'high', 'entry': 55000, 'mid': 100000, 'senior': 180000, 'salary': 100000, 'description': 'Design programmes promoting gender equality and social inclusion.', 'education': 'BA Gender Studies or Social Sciences', 'skills': 'gender analysis, policy advocacy, M&E, report writing', 'growth': '20%'},
    {'name': 'Humanitarian Aid Worker', 'category': 'NGO', 'demand': 'high', 'entry': 50000, 'mid': 95000, 'senior': 170000, 'salary': 95000, 'description': 'Deliver emergency relief and recovery programmes in crisis-affected areas.', 'education': 'BA or BSc + humanitarian certifications', 'skills': 'emergency response, logistics, WASH, food security, Sphere standards', 'growth': '15%'},
    {'name': 'County Government Officer', 'category': 'NGO', 'demand': 'high', 'entry': 40000, 'mid': 75000, 'senior': 130000, 'salary': 75000, 'description': 'Implement county government programmes in the devolved governance system.', 'education': 'BA Public Administration', 'skills': 'public administration, devolution, budget management, stakeholder liaison', 'growth': '15%'},
    # ── Fintech & Emerging ────────────────────────────────────────────────
    {'name': 'Fintech Product Manager', 'category': 'Technology', 'demand': 'very_high', 'entry': 90000, 'mid': 170000, 'senior': 300000, 'salary': 170000, 'description': 'Lead development of financial technology products for African markets.', 'education': "Bachelor's in CS or Business; MBA a strong asset", 'skills': 'product management, user research, agile, financial services, roadmapping', 'growth': '38%'},
    {'name': 'Solar Energy Technician', 'category': 'Technical', 'demand': 'very_high', 'entry': 35000, 'mid': 65000, 'senior': 110000, 'salary': 65000, 'description': 'Install, maintain, and repair solar panels and off-grid energy systems across Kenya.', 'education': 'TVET Diploma in Electrical or Renewable Energy', 'skills': 'solar installation, wiring, battery systems, troubleshooting', 'growth': '45%'},
    {'name': 'Air Traffic Controller', 'category': 'Technical', 'demand': 'high', 'entry': 90000, 'mid': 170000, 'senior': 300000, 'salary': 170000, 'description': 'Coordinate safe movement of aircraft in Kenyan airspace.', 'education': 'KCAA Air Traffic Control certification', 'skills': 'radar operation, radio communication, flight rules, emergency procedures', 'growth': '15%'},
    {'name': 'Agriculture Irrigation Engineer', 'category': 'Agriculture', 'demand': 'high', 'entry': 70000, 'mid': 130000, 'senior': 220000, 'salary': 130000, 'description': 'Design water supply and irrigation systems for agriculture.', 'education': 'BSc Agricultural or Civil Engineering', 'skills': 'hydraulics, irrigation design, GIS, water resource management', 'growth': '20%'},
    {'name': 'Food Scientist', 'category': 'Agriculture', 'demand': 'high', 'entry': 55000, 'mid': 100000, 'senior': 170000, 'salary': 100000, 'description': 'Develop, test, and improve food products and processing methods.', 'education': 'BSc Food Science and Technology', 'skills': 'food chemistry, quality control, HACCP, sensory evaluation', 'growth': '18%'},
    {'name': 'Aquaculture Specialist', 'category': 'Agriculture', 'demand': 'medium', 'entry': 50000, 'mid': 90000, 'senior': 150000, 'salary': 90000, 'description': 'Manage fish and seafood farming operations for food production.', 'education': 'BSc Aquaculture or Fisheries', 'skills': 'fish husbandry, water quality, disease management, production', 'growth': '15%'},
]
