# Generated by Django 6.0.1 on 2026-01-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('skill', 'Skill Development'), ('promotion', 'Get Promotion'), ('career_switch', 'Career Switch'), ('salary', 'Salary Increase'), ('leadership', 'Leadership Role'), ('entrepreneurship', 'Start Business')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='not_started', max_length=20)),
                ('priority', models.IntegerField(default=3)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('milestones', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='CoachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic Coaching'), ('premium', 'Premium Coaching'), ('enterprise', 'Enterprise Coaching')], max_length=20)),
                ('description', models.TextField()),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=list)),
                ('ai_sessions_per_month', models.IntegerField(default=0)),
                ('human_sessions_per_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_kes'],
            },
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('ai', 'AI Coaching Session'), ('human', 'Human Coach Session'), ('hybrid', 'Hybrid Session')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('user_input', models.TextField(blank=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('course', 'Online Course'), ('book', 'Book'), ('article', 'Article'), ('video', 'Video'), ('podcast', 'Podcast'), ('tool', 'Tool/Software'), ('event', 'Event/Conference'), ('community', 'Community/Forum')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('is_local', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('completed_by_user', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recommended_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoachingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('pending', 'Pending Payment')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_sessions_used', models.IntegerField(default=0)),
                ('human_sessions_used', models.IntegerField(default=0)),
                ('last_reset_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
