# Generated by Django 6.0.1 on 2026-01-15 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careergoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='career_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='coaching.careergoal'),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_sessions_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careergoal',
            name='coaching_sessions',
            field=models.ManyToManyField(blank=True, related_name='related_goals', to='coaching.coachingsession'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='coaching_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='coaching.coachingsession'),
        ),
        migrations.AddField(
            model_name='resourcerecommendation',
            name='coaching_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_recommendations', to='coaching.coachingsession'),
        ),
        migrations.AddField(
            model_name='usercoachingsubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='coaching.coachingplan'),
        ),
        migrations.AddField(
            model_name='usercoachingsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='coaching.usercoachingsubscription'),
        ),
    ]
