# Generated by Django 6.0.1 on 2026-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='average_kcse_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Average KCSE Score'),
        ),
        migrations.AddField(
            model_name='school',
            name='boarding_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('faith_based', 'Faith-Based'), ('community', 'Community')], default='public', max_length=50, verbose_name='School Category'),
        ),
        migrations.AddField(
            model_name='school',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='day_scholar_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='has_computer_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='has_science_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='mission_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='physical_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='subjects_offered',
            field=models.ManyToManyField(blank=True, to='recommendations.subject'),
        ),
        migrations.AddField(
            model_name='school',
            name='university_transition_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='University Transition Rate (%)'),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='vision_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_performance',
            field=models.CharField(choices=[('excellent', 'Excellent (A / 80-100%)'), ('good', 'Good (B / 65-79%)'), ('average', 'Average (C / 50-64%)'), ('below_average', 'Below Average (D / 40-49%)'), ('poor', 'Poor (E / 0-39%)'), ('not_applicable', "Not Applicable / Haven't Started")], default='good', help_text='Select your average academic performance level', max_length=20, verbose_name='Overall Academic Performance'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='career_interests',
            field=models.TextField(blank=True, help_text='Specific careers or fields you are interested in', verbose_name='Career Interests'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='extracurricular_activities',
            field=models.TextField(blank=True, help_text='Clubs, sports, or other activities you participate in', verbose_name='Extracurricular Activities'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_assessment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_profile_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learns_best_evening',
            field=models.BooleanField(default=False, help_text='Are you most productive in the evening?', verbose_name='Learns Best in Evening'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learns_best_morning',
            field=models.BooleanField(default=False, help_text='Are you most productive in the morning?', verbose_name='Learns Best in Morning'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='prefers_group_study',
            field=models.BooleanField(default=False, help_text='Do you prefer studying in groups?', verbose_name='Prefers Group Study'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='prefers_individual_study',
            field=models.BooleanField(default=True, help_text='Do you prefer studying alone?', verbose_name='Prefers Individual Study'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completion',
            field=models.IntegerField(default=0, help_text='Percentage of profile completion', verbose_name='Profile Completion (%)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='strongest_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects you excel in', related_name='strong_for_students', to='recommendations.subject', verbose_name='Strongest Subjects'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weakest_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects you find difficult', related_name='weak_for_students', to='recommendations.subject', verbose_name='Challenging Subjects'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Administrator'), ('school', 'School'), ('teacher', 'Teacher'), ('parent', 'Parent')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='School Code'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('national', 'National School'), ('county', 'County School'), ('private', 'Private School'), ('boarding', 'Boarding School'), ('day', 'Day School'), ('mixed', 'Mixed Day & Boarding'), ('boys', 'Boys Only'), ('girls', 'Girls Only'), ('special_needs', 'Special Needs School'), ('international', 'International School')], default='county', max_length=50, verbose_name='School Type'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='career_aspirations',
            field=models.TextField(blank=True, help_text='Describe your career goals and interests'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4'), ('college', 'College/University'), ('gap_year', 'Gap Year'), ('recent_graduate', 'Recent Graduate'), ('post_secondary', 'Post-Secondary Training')], default='form4', max_length=20, verbose_name='Current Grade Level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='kcpe_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter your KCPE score (0-500)', max_digits=5, null=True, verbose_name='KCPE Score'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='kcse_score',
            field=models.CharField(blank=True, help_text='Enter your KCSE grade (e.g., A, B+, C)', max_length=10, verbose_name='KCSE Grade'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['county'], name='users_schoo_county_67b11d_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['type'], name='users_schoo_type_1ca20f_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['is_active'], name='users_schoo_is_acti_17c04a_idx'),
        ),
    ]
