# Generated by Django 6.0.1 on 2026-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(choices=[('class7', 'Class 7 / Junior Secondary'), ('class8', 'Class 8 / Junior Secondary (Final)'), ('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4 (KCSE Candidate)'), ('form4_complete', 'Completed Form 4 — Awaiting Results'), ('gap_year', 'Gap Year — Deciding Next Steps'), ('diploma', 'Diploma / Certificate Programme'), ('year1', 'University — Year 1'), ('year2', 'University — Year 2'), ('year3', 'University — Year 3'), ('year4', 'University — Year 4 / Final Year'), ('postgrad', 'Postgraduate (Masters / PhD)'), ('working', 'Working — Considering Returning to School'), ('career_change', 'Career Change — Re-evaluating Direction'), ('recent_graduate', 'Recent Graduate — Job Seeking')], default='form4_complete', max_length=20, verbose_name='Current Grade Level'),
        ),
    ]
