# Generated by Django 6.0.1 on 2026-01-15 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_coach', '0001_initial'),
        ('assessments', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicoachlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='coachingplan',
            name='learning_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.learningstyle'),
        ),
        migrations.AddField(
            model_name='coachingplan',
            name='personality_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.personalitytype'),
        ),
        migrations.AddField(
            model_name='coachingplan',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coachingplan', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='aicoachlog',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_coach.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_coach.conversation'),
        ),
        migrations.AddField(
            model_name='resourcerecommendation',
            name='coaching_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ai_coach.coachingplan'),
        ),
    ]
